### ISSUE TITLE
Missing npm publish for --exlcudePrivate option

### ISSUE THREAD

**Issue by workfel** [TypeStrong/typedoc#302] opened 2016-10-07 08:17 UTC
Hello ! 
I want to use the exlcudePrivate option, but this version is not published on npm.

The last time of the package has published was 34 days ago and the commit for #293 is 16 days ago.

Thank you

**Comment by blakeembrey** [comment] 2016-10-11 21:00
Duplicate of https://github.com/TypeStrong/typedoc/issues/295. If a feature is urgent, please search existing issues and comment there. I'd recommend building it yourself as well, as releases will occur when they can be properly tested. That feature alone still contains bugs, hence there wasn't a release immediately because it was untested. 

I have limited time myself and without a full-time maintainer of this project I tend to unsubscribe when I'm burnt out on reports like this ☹️

**Closed by blakeembrey** 2016-10-11 21:00 UTC
