### ISSUE TITLE
Support for property access such as Type['prop']

### ISSUE THREAD

**Issue by bradennapier** [TypeStrong/typedoc#1335] opened 2020-07-06 19:01 UTC
## Search Terms

- property access
- type properties

## Problem

```typescript
type Example {
   foo: 'bar' | 'baz'
}

/** Documentation generated is just plain text */
function someFunc(v: Example['foo']) {

}
```

![image](https://user-images.githubusercontent.com/15365418/86629441-6eeabb00-bf99-11ea-80f3-968dde10c2e1.png)

Sorry if there is already some other manner which it can be access with.  Although that is the typescript-method so I am assuming not :)

## Suggested Solution

The TS compiler API should be providing this information, although I am not versed on how the exact configuration is setup for TypeDoc at the moment.

- MAJOR bonus points if it even grabs the documentation description from that and displays it inline <3

![image](https://user-images.githubusercontent.com/15365418/86629488-81fd8b00-bf99-11ea-877f-b48b9c699790.png)

**Comment by Gerrit0** [comment] 2020-07-08 02:39
This looks like a duplicate of #1226 to me.

Pulling in the documentation is really tricky. The TS compiler/language server does a ton of magic behind the scenes to get everything to work. I think it is out of scope for TypeDoc. We don't do this anywhere else, and TypeDoc is already plenty complex without trying to duplicate the language service...

**Closed** 2020-11-28 02:20 UTC
Labels: enhancement
