### ISSUE TITLE
Typescript 2.0 support

### ISSUE THREAD

**Issue by Spittal** [TypeStrong/typedoc#258] opened 2016-07-21 01:07 UTC
Currently I can't seem to get typedoc to work with a typescript 2.0 project. It fails with these errors:

```
Error: Unknown option `lib.0`.
Error: Unknown option `lib.1`.
Error: Unknown option `strictNullChecks`.
Error: Unknown option `baseUrl`.
Error: Unknown option `types.0`.
Error: Unknown option `types.1`.
Error: Unknown option `types.2`.
Error: Unknown option `types.3`.
Error: Unknown option `types.4`.
Error: Unknown option `types.5`.
Error: Unknown option `types.6`.
Error: Unknown option `types.7`.
Error: Unknown option `types.8`.
```

**Comment by blakeembrey** [comment] 2016-07-21 01:08
Closing as a duplicate of https://github.com/TypeStrong/typedoc/issues/234.

**Comment by blakeembrey** [comment] 2016-07-21 01:09
I updated the title in the linked issue to make it clearer, thanks!

**Closed by blakeembrey** 2016-07-21 01:08 UTC
