### ISSUE TITLE
Exclude does not work

### ISSUE THREAD

**Issue by Ezak91** [TypeStrong/typedoc#1928] opened 2022-05-09 08:19 UTC
My typedoc.json

```
{
  "exclude": "node_modules/@inovua/reactdatagrid-community/index.d.ts",
  "out": "docs"
}
```

The command
`typedoc --options typedoc.json src`

The error
```

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:49:38 - error TS2304: Cannot find name 'TypeComputedProps'.

49     hook: (props: {}, computedProps: TypeComputedProps, computedPropsRef: import("react").MutableRefObject<any>) => {  
                                        ~~~~~~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:50:38 - error TS2304: Cannot find name 'TypeRowProps'.

50         onRowContextMenu: (rowProps: TypeRowProps, event: import("react").SyntheticEvent<Element, Event>) => void;
                                        ~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:52:54 - error TS2304: Cannot find name 'TypeRowProps'.

52         showRowContextMenu: (alignTo: any, rowProps: TypeRowProps, cellProps: TypeCellProps, onHide: (...args: any[]) => void) => void;
                                                        ~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:52:79 - error TS2304: Cannot find name 'TypeCellProps'.

52         showRowContextMenu: (alignTo: any, rowProps: TypeRowProps, cellProps: TypeCellProps, onHide: (...args: any[]) => void) => void;
                                                                                 ~~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:53:58 - error TS2304: Cannot find name 'TypeCellProps'.

53         showColumnContextMenu: (alignTo: any, cellProps: TypeCellProps, cellInstance: any, onHide: (...args: any[]) => void) => void;
                                                            ~~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:76:46 - error TS2304: Cannot find name 'TypeComputedProps'.

76     renderColumnContextMenu: (computedProps: TypeComputedProps, computedPropsRef: import("react").MutableRefObject<any>) => any;
                                                ~~~~~~~~~~~~~~~~~

Error: node_modules/@inovua/reactdatagrid-community/index.d.ts:77:43 - error TS2304: Cannot find name 'TypeComputedProps'.

77     renderRowContextMenu: (computedProps: TypeComputedProps, computedPropsRef: import("react").MutableRefObject<any>) => any;
```

**Comment by Gerrit0** [comment] 2022-05-09 12:40
This is working as intended. Those errors are coming from TypeScript, not TypeDoc. `exclude` is used to filter what is documented, but the whole project still needs to compile in order for documentation to be generated. If you run `npx tsc`, you'll get the same errors.

The easiest fix for this is turning on `skipLibCheck` in your tsconfig.

**Comment by r-hede** [comment] 2022-05-10 12:12
Unfortunately not, I have the same error whereas I have no error when I run `npx tsc`.

I specify that `skipLibCheck` is set to `true` in my `tsconfig.json` file.

**Comment by Ezak91** [comment] 2022-05-11 11:47
skipLibCheck fix it for me

and the owner of the component fix the error too

**Closed** 2022-05-11 11:47 UTC
Labels: bug, no bug
