### ISSUE TITLE
Module-level documentation is ignored

### ISSUE THREAD

**Issue by demurgos** [TypeStrong/typedoc#743] opened 2018-04-06 22:51 UTC
I expect module-level documentation to be generated for the following file:

```typescript
/**
 * This is the module-level documentation. This module exports greeting functions.
 */

import fs from "fs";

export function greetFs() { fs.writeFileSync("hello.txt", "Hello, World!");}
export function greetConsole() { console.log("Hello, World!");}
```

This module-level documentation is not emitted because there is a single comment at the top of the module and it is ignored because of this code:

https://github.com/TypeStrong/typedoc/blob/1d9e8f23202663a49e43df64efddaf8be8c7e054/src/lib/converter/factories/comment.ts#L91-L93

Why is this test there?! Could you remove it or add a comment explain why it's there? Or fix the issue in another way?

The current workaround is to use a placeholder comment to avoid this test:

```typescript
/**
 * This is the module-level documentation. This module exports greeting functions.
 */

/** Placeholder to fix module-level documentation generation */

import fs from "fs";

export function greetFs() { fs.writeFileSync("hello.txt", "Hello, World!");}
export function greetConsole() { console.log("Hello, World!");}
```

**Comment by aciccarello** [comment] 2018-04-06 22:55
Thanks for the report, however I believe this is a duplicate of #603 so I'm going to close in favor of that one. Please add a comment if you think there is information missing there.

**Closed by aciccarello** 2018-04-06 22:55 UTC

**Comment by demurgos** [comment] 2018-04-06 23:31
Thank you. I used the search tool but couldn't find this issue. I'll comment there.
