### ISSUE TITLE
commonjs named exports are merged into `export=` when not function/class

### ISSUE THREAD

**Issue by hugomrdias** [TypeStrong/typedoc#1508] opened 2021-02-15 17:17 UTC
## Search terms

commonjs
named exports
module.exports

## Expected Behavior

all named exports should show in the navigation

## Actual Behavior

all named exports are merged into `export=` when at least one of the named exports isn't a function/class

## Steps to reproduce the bug

https://codesandbox.io/s/typedoc-test-w69ry?file=/src/index.js

## Environment

-   Typedoc version: 0.20
-   TypeScript version: 4.1.3
-   Node.js version: all
-   OS: all

**Comment by Gerrit0** [comment] 2021-02-16 02:42
I am *so* close to saying I don't care about the horrible thing that is `module.exports`.

I removed `o1` from your demo, and see the same behavior, with a single `export=` member having two function properties... which indicates this might be a dupe of #1422.

**Comment by hugomrdias** [comment] 2021-02-16 11:54
i can't reproduce that maybe it was some cache in codesandbox
<img width="727" alt="Screenshot 2021-02-16 at 11 49 48" src="https://user-images.githubusercontent.com/314190/108059300-35108580-704d-11eb-82db-03c3ef7c219d.png">

i spotted this error with the following
```js
const obj1 = { key :value }

module.exports = {
  fn1,
  fn2,
  obj1: Object.freeze(obj1)
}
```

changing this code to
```js
const obj1 = { key :value }
Object.freeze(obj1)
module.exports = {
  fn1,
  fn2,
  obj1
}
```
solves the issue, so seems to be when you define the name export directly in the `module.export ={}` block.

**Comment by Gerrit0** [comment] 2021-06-15 03:35
Having spent more time looking into this, I've decided that there's no good way to fix this with the existing implementation of converters. TypeDoc relies on TypeScript's symbol organization to figure out how to document code, and TypeScript's symbol flags are set in such a way here that documenting module.exports as an object is the way to go. Trying to detect this edge case is proving too hacky.

**Closed by Gerrit0** 2021-06-15 03:35 UTC
Labels: bug, design-limitation
