### ISSUE TITLE
Add support for adding markdown pages

### ISSUE THREAD

**Issue by mayank1513** [TypeStrong/typedoc#2565] opened 2024-05-01 03:36 UTC
## Search Terms

pages, markdown, md

## Problem

Similar issue was reported earlier as well. However, it was closed citing a plugin. However, the plugins developed for one version do not work with the other. Also, we don't want to be locked to lower version of TypeScript to use Typedoc with lower version.

## Suggested Solution

Please create a feature to automatically pick up markdown files from specified directory or path and include that in documentation.

**Comment by mayank1513** [comment] 2024-05-01 04:39
As of now, I just employed a quick hack - https://react18-tools.github.io/react18-global-store/

This suggests that it shouldn't be very difficult to add this feature with a little better aesthetics to the library.

**Comment by Gerrit0** [comment] 2024-05-01 11:48
Duplicate of #247, this is the feature I'm hoping to include in the next typedoc minor release.

**Comment by mayank1513** [comment] 2024-05-01 11:50
Thanks. Let me know if I can help in any way. Do you have any open PR for this that I can review and see if I can add anything to it?

**Comment by Gerrit0** [comment] 2024-05-01 12:57
Nothing up yet, I'm hoping to get to a working POC this weekend, or possibly the next.

**Comment by Gerrit0** [comment] 2024-05-04 16:54
0.26.0-beta.0 is up with this, announcement at https://github.com/TypeStrong/typedoc/issues/2567

**Closed** 2024-06-16 21:34 UTC
Labels: duplicate, enhancement
