### ISSUE TITLE
Inclusion pattern doesn't work

### ISSUE THREAD

**Issue by diavrank** [TypeStrong/typedoc#1399] opened 2020-11-22 04:12 UTC
## Search terms

inclusion patterns, negated, complement

## Expected Behavior

I expect to select files which have an ending of 'Ctrl.ts' using negation operator in **--exclude flag**.

## Actual Behavior

The "!" operator does not seem to be working. I am using the next command:
```
typedoc --out docs --ignoreCompilerErrors --exclude '!**/*Ctrl.ts' --excludeExternals imports/api
```
And directory structure is the following:
```shell
app-web git:(dev) tree imports/api
imports/api
├── Binnacle
│   └── BinnacleCtrl.ts
├── Permissions
│   ├── Permission.ts
│   ├── PermissionsCtrl.ts
│   └── PermissionsPubs.ts
├── Profiles
│   ├── Profile.ts
│   ├── ProfileSeeder.ts
│   ├── ProfilesCtrl.ts
│   ├── ProfilesPubs.ts
│   └── ProfilesServ.ts
├── Rest
│   ├── ResponseEntity.ts
│   ├── UsersRest.ts
│   ├── config.ts
│   └── upload-middleware.ts
├── SystemOptions
│   ├── SystemOption.ts
│   └── SystemOptionsCtrl.ts
└── Users
    ├── User.ts
    ├── UserPresenceConfig.ts
    ├── UsersCtrl.ts
    ├── UsersPubs.ts
    └── UsersServ.ts


```

I am trying to select files that have the ending **Ctrl.js**, this is like a **inclusion pattern** or the complement of the exclusion _'**/*Ctrl.ts'_ which does work. When I execute the inclusion pattern, no data is exported. However, if I execute:

```
typedoc --out docs --ignoreCompilerErrors --exclude '**/*Ctrl.ts' --excludeExternals imports/api
```
This does work because is not showing files with ending **Ctrl.ts**. So, I want to get the complement of this but when I try to use negation operation **(!)**, it doesn't display anything.

I already searched in different places the solution but I haven't had luck.

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.5
-   Node.js version: 12.18.4
-   OS: Mac OS Big Sur

**Comment by Gerrit0** [comment] 2020-11-25 21:33
I can't seem to reproduce this, is it possible your shell is expanding the alias?

**Comment by diavrank** [comment] 2020-12-04 01:23
Hi @Gerrit0 , I did a mini example in order to reproduce it.

Inside on it, there is a readme file with the steps to follow.

[myapp.zip](https://github.com/TypeStrong/typedoc/files/5639994/myapp.zip)

Let me know if you have any question.

**Comment by Gerrit0** [comment] 2020-12-05 19:43
Ah, that makes a whole lot more sense now! My test case didn't have an extra directory, which made all the difference.

What TypeDoc is doing:
- Expand imports/api - getting each of the folders within that
- Loop over each folder, checking imports/api/FOLDER against the exclude pattern - this matches since it doesn't end in Ctrl.ts, and each folder is marked as excluded

The first obvious fix for this is only checking exclude patterns on files - but that potentially causes other issues since the pattern `node_modules` would no longer exclude anything in that folder... I think I'm okay with this, especially with the changes in 0.20 which will result in `--exclude` not being used as frequently.

**Closed** 2021-09-10 16:32 UTC
Labels: bug, reproduced
