### ISSUE TITLE
TypeScript Paths Make TypeDoc Call Everything External

### ISSUE THREAD

**Issue by ProfessorManhattan** [TypeStrong/typedoc#1185] opened 2020-01-19 10:06 UTC
TypeDoc is labeling all the files in an Angular app as external when you click on the links on the right. Did I not set up the configuration right?

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
All the code in the src/app folder should be internal.

## Actual Behavior
Everything shows up as external.

## Steps to reproduce the bug
```
npm install -g @angular/cli
ng new TestApp
cd TestApp
typedoc --tsconfig tsconfig.app.json --exclude **/*.spec.ts src/app
```
Open the documentation, click on any of the files and they all say "External ...."

## Environment
Windows 10
C:\Users\x\OneDrive\Documents\Websites\x\docs>node -v
v10.16.0

C:\Users\x\OneDrive\Documents\Websites\x\docs>typedoc --version

TypeDoc 0.16.7
Using TypeScript 3.7.5 from C:\Users\x\AppData\Roaming\nvm\v10.16.0\node_modules\typedoc\node_modules\typescript\lib

**Comment by Gerrit0** [comment] 2020-01-19 22:08
Do you mean the "External Module" label? That's a misnomer that will be fixed relatively soon with #1184, your files are likely not actually marked as external.

**Comment by ProfessorMegabyte** [comment] 2020-01-20 00:34
@Gerrit0 They actually were marked External until I included the "include": ["./src/**/*.ts"] in tsconfig.json. Before that I just had a "files": ["./src/main.ts", "./src/polyfills.ts"], declaration.

**Comment by Gerrit0** [comment] 2020-01-21 18:26
I can't reproduce this with the commands you specified above. Note that the externals box is unchecked, which would hide any externals, but AppModule is included, indicating that it is not external.

![image](https://user-images.githubusercontent.com/19329837/72831713-9abef200-3c40-11ea-8071-970ab888b486.png)

**Closed** 2020-04-06 00:48 UTC
Labels: awaiting response, bug
