### ISSUE TITLE
Improve signature description for cascade arrow functions

### ISSUE THREAD

**Issue by lanyusan** [TypeStrong/typedoc#1289] opened 2020-04-30 06:13 UTC
## Search Terms
cascade arrow function

## Problem

Documentation for cascade arrow function is not correct.

A real life example:

```
export const shiftNode = <T = unknown, N = unknown>(params: {
  /** node or tag's path. if node, should not include the node itself. if tag, should include the tag's node */
  path: IdType[]
  /** id of the node or tag */
  id: IdType
  /** shift before or after */
  before?: boolean
}) => (shape: Shape<T, N>): Shape<T, N> => 

```

The signature generated is: 
```
shiftNode<T, N>(params: { before?: undefined | false | true; id: IdType; path: IdType[] }): (Anonymous function)
```
And doc for `params` of the second arrow function is lost.

## Suggested Solution

Generate full arrow function chain signature, all param documentation and return value documentation.

**Comment by Gerrit0** [comment] 2020-05-13 03:32
Duplicate of #1098

**Closed by Gerrit0** 2020-05-13 03:32 UTC
Labels: duplicate, enhancement
