### ISSUE TITLE
JSON output missing flags

### ISSUE THREAD

**Issue by mcaden** [TypeStrong/typedoc#888] opened 2018-10-24 15:57 UTC
I'm using typedoc (HEAD, because I needed 3074344f8e655c96acdc93433e22e33fc190eba0) to generate json output to feed to another tool.

The problem is, the resulting JSON for my exported classes and modules has `"flags": {}` - no actual flags.

Expected:

    "flags": {
        "isExported": true
    }

This is true for the entire file, multiple projects.

**Comment by mcaden** [comment] 2018-10-24 15:58
@Gerrit0 it appears if I revert a2fab7cf1b5957c2e05ffd3882583dcf812ea8c7 then the issue is resolved so it appears on the surface to be something in that PR?

**Comment by Gerrit0** [comment] 2018-10-24 21:38
Unfortunate that that commit is the one causing the issue... it's way to large to easily figure out what the issue is. Do you have a failing test I could look at?

**Comment by mcaden** [comment] 2018-10-25 16:37
So as it stands, there are 2 tests failing. One looks to be a mess of HTML output I don't have time to diff right now but I looked at the one in decorators and it seems to simply be an issue of line-endings.

`"options": "{\n    name: 'Name of class'\n}"` (Expected)
`"options": "{\r\n    name: 'Name of class'\r\n}"` (Actual)

This looks like an easy fix but I'm not sure where and it's completely unrelated. Perhaps something with me building/testing on Windows?

However, in looking at it I found something interesting... in `src\test\converter\decorators\decorators.ts` if you look, the class **is not exported**. YET, the spec.json contains the `"isExported": true`. AND, if you export the class... `export class DecoratedClass` _**BOOM**_ repro - `"flags": {}`. So it looks like something else funky is going on. It looks like tests are passing that technically shouldn't if I'm understanding "isExported" correctly.

It appears to be doing the opposite of what I would expect. If that's the case though, I'm not sure why more tests aren't failing - specifically the ones having to do with export!

**Comment by Gerrit0** [comment] 2018-10-25 17:43
The decorator test should be fixed by #872, I messed up when adding a gitattributes file to the project, so git isn't checking files out with the correct line endings.

With that fix applied, I did a a fresh clone and see all tests passing.

For decorators.ts - `isExported` is only applied to the module itself according to the [specs.json](https://github.com/TypeStrong/typedoc/blob/master/src/test/converter/decorators/specs.json#L13) file. Adding `export class DecoratedClass` looks to me like it correctly adds the flags.

**Comment by mcaden** [comment] 2018-10-25 21:16
Yeah, the bit about `decorators` test ended up a red herring because I goofed in reading the console output. The only thing I can think of is the tests seem to be using "file" mode. I'm using angular with modules. I've done the following to reproduce. Since I'm seeing it in Angular I used the dotnet core template to quickly spin up a reproducible app.

    dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*"
    dotnet new angular -o tdtest
    cd tdtest\ClientApp
    npm i --save-dev https://github.com/TypeStrong/typedoc.git#a2fab7cf1b5957c2e05ffd3882583dcf812ea8c7

(that last package is where your commit comes in)
Add to package.json under "scripts":

    "docs": "typedoc --json ./tsapi.json ./src --tsconfig ./src/tsconfig.app.json --exclude **/*.spec.ts"

Then: `npm run docs`

Open tsapi.json.

**Expected**: Since all the modules, components, etc... are written as `export class ...` I'd expect this to be _somewhere_ in the file.:

    "flags": {
        "isExported": true
    }

**Actual**: Not a single class or module has any flags in the entire file.

    "flags": {}

If the commit of typedoc before yours is used the classes have the right flags. For convenience I've attached the front-end portion of the application I generated (minus node_modules, you'll need to `npm install`).

[ClientApp.zip](https://github.com/TypeStrong/typedoc/files/2516308/ClientApp.zip)

**Comment by Gerrit0** [comment] 2018-10-26 06:37
Thanks for the zip! It helped me figure out where the problem is fairly quickly. You were right that that PR was what caused it. I tried to rewrite part the [ReflectionFlags](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/abstract.ts#L102) class since it was difficult to understand in the previous implementation, and in doing so I broke this. It's really odd that this wasn't caught by the tests as rendering flags in the JSON is tested at least partially...

Should be fixed with #889

**Comment by aciccarello** [comment] 2018-10-26 13:50
Awesome! Great work narrowing that down!

**Closed** 2018-10-26 13:49 UTC

**Comment by mcaden** [comment] 2018-10-26 14:02
This does indeed look fixed, thanks! Any thoughts on why it seemed to function fine in the tests?

**Comment by Gerrit0** [comment] 2018-10-26 15:51
After looking into it further, I believe your initial assessment was correct. It seems to be because the code was run in `file` mode, so the only flags object that ever had anything was the module. The module code has it's own `toObject` method which I did modify to correctly handle the restructured `ReflectionFlags` class [here](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/abstract.ts#L556).

Looks like I need to see if there's a feasible way to add test for multiple modes.

**Comment by SebHoffmRS** [comment] 2021-08-05 07:28
@Gerrit0 this seems to be broken again (I'm using 0.21.5)

**Comment by Gerrit0** [comment] 2021-08-05 12:41
The isExported flag was removed in 0.20. TypeDoc only documents exported members now.

**Comment by SebHoffmRS** [comment] 2021-08-05 12:45
@Gerrit0 oh thanks, good to know! Then this is a bug/incompatibility in type2docfx, I'll update their issue.
