### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by taoqf** [TypeStrong/typedoc#648] opened 2017-11-13 02:56 UTC
I came to a problem with the double quote, modules/*.html file generated will have a _ prefix, and I will get a 404 when I put these files on my website on github. It seems github will hide these files. Is there a way I could generate files without _?

**Comment by aciccarello** [comment] 2017-11-13 16:38
@taoqf Thanks for reporting but there is already a closed issue for this. The solution is to include a `.nojekyll `file at the document root. I would like to eventually see the underscores removed from external modules though.

Closing as duplicate of #149

**Closed by aciccarello** 2017-11-13 16:38 UTC

**Comment by taoqf** [comment] 2017-11-14 02:52
Thanks
