### ISSUE TITLE
Module pollution - a few questions on the design of Typedoc

### ISSUE THREAD

**Issue by NearAutomata** [TypeStrong/typedoc#774] opened 2018-05-18 00:01 UTC
I just tried out `typedoc` and really like it thus far. Unfortunately there are some flaws I don't understand yet which I'd like to know more about. For testing purposes I used the source files from the following folder structure:
<img width="256" alt="screen shot 2018-05-18 at 01 37 23" src="https://user-images.githubusercontent.com/32624319/40209162-0ed8948e-5a3e-11e8-807a-825051d177b6.png">
When I ran `typedoc` for the first time I got this output:
<img width="1257" alt="screen shot 2018-05-18 at 01 37 54" src="https://user-images.githubusercontent.com/32624319/40209174-23509c54-5a3e-11e8-9a0b-477577a5190c.png">
Basically every single TypeScript file was considered a single module in itself, even though I have one and only one type/class/interface per file. After turning on `--mode file` I got the following output:
<img width="1262" alt="screen shot 2018-05-18 at 01 38 10" src="https://user-images.githubusercontent.com/32624319/40209217-4efd6f3a-5a3e-11e8-8701-4e7fc6a3784d.png">
In the second example it is unfortunate that there is no way to distinguish which folders the specific classes/interface come from. This is even more obvious when adding another class with the same name in another folder. Although bad in design, it can actually happen in a library that is big enough. What happens is, that `typedoc` merges all classes/enums/interfaces with the same name and only creates one bullet point with all members and documentation comments merged.

The only useful plugin I found thus far is [asgerjensen/typedoc-plugin-external-module-map](https://github.com/asgerjensen/typedoc-plugin-external-module-map) which allows some minor grouping. In fact I consider that particular plugin to be useful to create a documentation for multiple projects that get grouped using the plugin.

I'd like to know whether you are aware of the documentations that erroneously get merged and would like to know which options or plugins I can leverage to bring some order into this chaos.

**Comment by aciccarello** [comment] 2018-08-09 04:32
Hello @NearAutomata, thanks for bringing up these points. Right now typedoc does not handle a directory structure very well but it is something that would be great to support better in the future. I'll close this as a duplicate of #379

**Closed by aciccarello** 2018-08-09 04:32 UTC
