### ISSUE TITLE
Expose applied decorators in generated docs

### ISSUE THREAD

**Issue by mattflix** [TypeStrong/typedoc#181] opened 2016-01-26 08:27 UTC
This is a feature request for TypeDoc to expose the decorator(s) applied to a type (such as class) in the generated doc.

For example, I assume I have defined a decorator named "serialize" that applies to classes.  When I write the following in my TypeScript source...

``` javascript
@serialize
class MyClass { }
```

...it would be awesome if the generated doc indicated that MyClass has been decorated with @serialize.  Currently, the generated doc does not expose this fact, but this sort of information can be _vital_ to understanding a complex system of types that makes sophisticated use of decorators.  

Of course, one would also be able to navigate to the decorator's own documentation from any such reference.

Going further, decorators often take arguments.  Ideally, the specific arguments values passed to the decorator should also be exposed in the generated docs.

For example, let's assume we have additional decorators that identify the "handler" class and another that lists "excluded" members (in an array).

``` javascript
@serialize
@handler(MyHandler)
@excluded([ "foo", "bar" ])
class MyClass { }
```

Again, it would be awesome if generated doc not only indicated that MyClass has been decorated with @handler and @excluded, but also listed the argument values passed to each decorator, with appropriate doc links as necessary.

For example, one would be able to navigate to the documentation for MyHandler, the value of the argument to @handler.

Lastly, my vote for the presentation of "applied decorators" in the generated doc would be to use a natural-looking syntax (as in the above examples), simply embellished with the necessary hyperlinks.

**Comment by aciccarello** [comment] 2017-02-03 07:00
Duplicate of #97?

**Comment by diosney** [comment] 2019-02-08 17:55
Useful to expose validations if using something like https://github.com/typestack/class-validator or other custom features.

**Comment by DanielSchaffer** [comment] 2019-03-15 04:34
@aciccarello I think these are separate things. I see #97 as basic support for calling out functions marked with `@decorator` as decorators (as opposed to being lumped in with other plain old functions). If I'm understanding @mattflix's request correctly, they're asking that the documentation for classes (and, I'm assuming, the other decorator targets - params, properties, and methods) gets rendered with any decorators applied in the source code. This is similar to how Microsoft includes attributes in their documentation (see https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader?view=netframework-4.7.2 for an example - note the `System.Runtime.InteropServices.ComVisible` attribute).

**Comment by mattflix** [comment] 2019-03-15 05:04
Yes, @DanielSchaffer summarizes my feature request exactly.

**Comment by aciccarello** [comment] 2019-03-15 06:13
That's a fair distinction. Thanks for clarifying.

**Comment by DanielSchaffer** [comment] 2019-03-18 23:48
@aciccarello Correct me if I'm wrong, but the data to support this should already exist. This really just needs some template work to render what's in the the `decorators` property in https://github.com/TypeStrong/typedoc-default-themes, right?

**Comment by DanielSchaffer** [comment] 2019-03-19 00:22
- [ ] Add icon set for decorators
- [ ] Add decorators signature partial, to be used as part of all types of signatures. Includes links to decorator documentation, as well as linked parameter values, if applicable
- [ ] Add `Decorators` documentation partial
- [ ] Add class declaration partial, similar to member declaration partial - e.g. `class Foo extends Bar implements Something {}`
- [ ] Add decorators to class declaration display (including linking to decorators and parameters)
- [ ] Add `Decorators` section to reflection template
- [ ] Add method/param/property decorators to member signature display

**Comment by Gerrit0** [comment] 2021-06-27 03:36
Until the TypeScript team has updated to the new decorators proposal, and moved support out of an `experimental` flag, I don't want to spend time on this.

TypeDoc does expose some decorator info in the model, so a custom theme could theoretically do this today

**Closed by Gerrit0** 2021-06-27 03:36 UTC
Labels: enhancement, wontfix
