### ISSUE TITLE
`Maximum call stack size exceeded` error starting from 0.25.3

### ISSUE THREAD

**Issue by ericmorand** [TypeStrong/typedoc#2451] opened 2023-12-04 07:04 UTC
## Search terms

Maximum call stack size exceeded

## Expected Behavior

With 0.25.2 building the documentation of Twing was working perfectly. I expect that a patch release doesn't break something that was working.

## Actual Behavior

Starting with 0.25.3 building the documentation of Twing fails with the error:

Maximum call stack size exceeded

## Steps to reproduce the bug

I'm investigating the code of typedoc itself and the changes that were made between 0.25.2 and 0.25.3 and will update this issue as soon as I find the culprit.

In the meantime, here is the job log of Twing:

https://gitlab.com/nightlycommit/twing/-/jobs/5671446717

## Environment

-   Typedoc version: 0.25.3 and 0.25.4
-   TypeScript version: 5.2.2
-   Node.js version: 16.20.2
-   OS: Ubuntu 20.04

**Comment by ericmorand** [comment] 2023-12-04 07:19
OK, I narrowed it to this reproductible test case:

```ts
type Foo =
    | FooA
    | FooB
;

interface BaseFoo<T extends string> {
    type: T;
    
    is<Type extends string>(type: Type): this is Foo & {
        type: Type;
    };
}

interface FooA extends BaseFoo<"A"> {
    
}

interface FooB extends BaseFoo<"B"> {

}
```

Using typedoc on this code will trigger the `Maximum call stack size exceeded` error.

**Comment by Gerrit0** [comment] 2023-12-04 13:30
Wow, that's a weird one. That was a pretty small release in terms of changes.. *Probably* related to the mixin handling improvements introduced there.

**Comment by Gerrit0** [comment] 2023-12-13 04:39
Ick. This is caused by the horribly hacky fix I put in for #2011...  According to TS, `Foo & { type: Type }` is *not* an intersection.... which happens to conflict with the intersection check I put in to deal with some terrible mixin code, where we actually should be converting this as an intersection.

Feels like the compiler API ought to be admitting that this is an intersection though, I've asked in the compiler API section in Discord, hopefully one of the compiler devs will tell me I'm being dumb...

**Comment by Gerrit0** [comment] 2023-12-27 18:47
Well, not completely dumb, but I'm surprised I hadn't realized before that if a type contains a union, the union *must* be present at the top level of the type, so TS is normalizing that type internally to be `(FooA & { type: Type }) | (FooB & { type: Type })`

The fix for this is to use the internal `origin` property to get the type before this transformation has been made.

**Closed** 2023-12-27 18:49 UTC
Labels: bug

**Comment by ericmorand** [comment] 2023-12-27 21:34
Amazing. Thanks a lot.
