### ISSUE TITLE
no documentation for tsx

### ISSUE THREAD

**Issue by macrozone** [TypeStrong/typedoc#1434] opened 2020-12-29 16:14 UTC
## Search terms

tsx, jsdoc

## Expected Behavior

jsdoc comments should be documented in ts and tsx files

## Actual Behavior

in tsx files, jsdoc block comments are ignored

## Steps to reproduce the bug

- somefile.tsx
- add some type with jsdoc
- generate documentation

## Environment

-   Typedoc version: 0.20.1
-   TypeScript version: 4.0.3
-   Node.js version: v12.13.1
-   OS: mac os big sur

**Comment by Gerrit0** [comment] 2020-12-29 16:33
I reacted `src/gh1434.tsx` with the following content and ran typedoc on it:

```tsx
import * as React from "react"
/** Some docs */
export const x = <span>hi</span>
```

Seems to be working correctly...

![image](https://user-images.githubusercontent.com/19329837/103299022-db7acb80-49b8-11eb-9fc4-194cea0ae9b3.png)

**Comment by macrozone** [comment] 2020-12-29 16:47
@Gerrit0 what command did you run?

i currently work on the docs for my editor library (https://github.com/react-page/react-page, beta branch). I tried to add it to a sub package there and i just ran

`yarn typedoc ./src/index.tsx --out api-doc`

i see a lot of missing docs there and it looks like all tsx files are concerned. Do i need to add some flag? is there some problem with the tsconfig?

**Comment by macrozone** [comment] 2020-12-29 16:48
@Gerrit0 would you mind to add an object type in your tsx file?

```

type Foo = {
  /** some bar property **/
   bar: string
}
```

**Comment by Gerrit0** [comment] 2020-12-29 17:21
I just ran `npx typedoc src/gh1434.tsx`

```ts
type Foo = {
  /** some bar property **/
   bar: string
}
```

This won't be documented - it isn't exported. In 0.20, TypeDoc will *only* document what is exported, because that is what your API surface is. The rest is implementation details that users don't care about. Change this to `export type` and TypeDoc will document it as expected.

**Comment by macrozone** [comment] 2020-12-29 20:13
@Gerrit0 sorry, of course i exported it. It also appears in the doc! just without any jsdoc (/** stuff @returns otherstuff **/). 

its really weird

**Comment by Gerrit0** [comment] 2020-12-29 20:47
That would be great, once exported it appears like this to me:

![image](https://user-images.githubusercontent.com/19329837/103313135-56a1a900-49dc-11eb-9aec-d18e36c5f3b7.png)

**Comment by Gerrit0** [comment] 2021-01-17 02:51
Closing as unactionable without a reproduction, please reopen if you are able to create a repro.

**Closed by Gerrit0** 2021-01-17 02:51 UTC
Labels: bug, needs reproduction
