### ISSUE TITLE
Not recognising documentation for class properties in JS files

### ISSUE THREAD

**Issue by danprince** [TypeStrong/typedoc#1255] opened 2020-03-30 10:05 UTC
It seems like Typedoc doesn't support the `@type` tag that TypeScript recommends using to add types to class properties in JavaScript projects.

Example from the [official handbook](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html).

```js
class C {
    constructor() {
        /** @type {number | undefined} */
        this.prop = undefined;
        /** @type {number | undefined} */
        this.count;
    }
}
```

I have a project which documents properties this way extensively, but none of them end up in the generated documentation (regardless of visibility modifiers etc).

```js
  /**
   * Font represents a bitmap font that will be used to render for a terminal.
   *
   * @param {object} settings
   * @param {string} settings.url The url for the font's image
   * @param {number} [settings.columns] The number of columns in the font's image
   * @param {number} [settings.rows] The number of rows in the font's image
   * @param {boolean} [settings.graphical] Specify whether the font is already colored
   * @param {number} [settings.transparentColor] Transparency key for the font image in numeric RGBA format
   */
  constructor({
    url,
    columns = 16,
    rows = 16,
    graphical = false,
    transparentColor = 0x00000000,
  }) {
    /**
     * @type {HTMLImageElement}
     * @readonly
     * @private
     */
    this.image = new Image();
    this.image.src = url;

    /**
     * The width (in characters) of this font.
     *
     * @readonly
     */
    this.columns = columns;

    /**
     * The height (in characters) of this font.
     *
     * @readonly
     */
    this.rows = rows;
```

The constructor, accessors and all the methods are present in the generated docs, but no properties.

![image](https://user-images.githubusercontent.com/1266011/77900607-350d6880-7276-11ea-8f06-bcb4389bf697.png)

**Comment by Gerrit0** [comment] 2020-03-30 12:22
The cause of this is that we currently find members by looking at the AST nodes. We should instead be using the type checker.

**Comment by danprince** [comment] 2020-03-30 14:19
Is using the type checker something that might happen in the short term future?

Might be naive (because I haven't been through the codebase) but what about just parsing property assignments for `this` inside the constructor, once you have the AST?

**Comment by Gerrit0** [comment] 2020-04-05 01:16
Unfortunately probably not very short term :/

Right now the whole converter structure is based on iterating over the nodes of a file. I'm guessing the type checker API wasn't nearly as complete when it was written so we couldn't just use it. Reworking the converters to use the type checker is something that needs to happen (maybe even for library mode to work, I've been running into a bunch of issues with the node based conversion)

It should be possible to look inside the constructor as you suggest should fix this, PR welcome if you'd like to give it a try. The code should probably be around here - https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/nodes/constructor.ts#L26

**Comment by Gerrit0** [comment] 2020-11-28 02:39
In 0.20, we get the properties in a reasonable manner, by asking the type checker... but are still relying on nodes in order to find the  comment, so they remain undocumented. Unfortunately, resolving this is... tricky. We can't use `symbol.getDocumentationComment()` to retrieve the comment (at least in all cases..) because that merges comments together on declaration-merged symbols, which is entirely undesirable. Still going to leave this open... but I'm not sure about a resolution.

![image](https://user-images.githubusercontent.com/19329837/100492266-bd832800-30e7-11eb-9448-a037f3a6d4d1.png)

**Comment by andyhall** [comment] 2021-05-31 06:51
Hi, just wanted to ping how useful it would be if this could be addressed. I've been delving into using `typedoc` for JS, and *almost* everything works beautifully. But this one issue is the blocker; the only workaround seems to be declaring typedefs for every class that duplicate every class property. (or use JSdoc, which unfortunately has a host of other problems..)

**Comment by Gerrit0** [comment] 2021-06-01 03:01
Well, turns out sometimes all that's necessary is a break of a few months... Literally a one line change to make this work.

**Comment by andyhall** [comment] 2021-06-01 08:39
Brilliant, thanks!

**Closed** 2021-06-18 02:42 UTC
Labels: bug, js
