### ISSUE TITLE
#FeatureRequest Support Watch mode

### ISSUE THREAD

**Issue by unsafecode** [TypeStrong/typedoc#403] opened 2017-02-03 09:55 UTC
When working on a complex codebase, it would be useful to have a watch mode, so you would be able to see changes faster.

**Comment by aciccarello** [comment] 2017-02-03 15:24
Duplicate of #207

**Comment by IanEdington** [comment] 2020-01-17 04:06
I don't think this is the same as `Incremental build`. Supporting a watch mode could still do a full build each time. The benefit would be increasing developer productivity while developing docs

**Comment by Gerrit0** [comment] 2020-01-17 04:36
It isn't exactly the same, but a (builtin) watch mode without incremental builds kind of defeats the gains from it being built in. TypeDoc will always take at least ~4 seconds to build even a one file project because that's the overhead from starting the TypeScript compiler. In practice, it will probably take longer... while it could be built in, I'm not convinced it is worth the extra complexity until there is a speed benefit to having this built in.

It's easy to use [onchange](https://www.npmjs.com/package/onchange) to do this yourself,

```bash
onchange 'src/**/*.ts' -- npx typedoc --out docs/ src/
```

**Comment by Gerrit0** [comment] 2021-01-24 21:42
What on earth was I thinking? Watch and incremental are very different things. Incremental support is very different from watch. Yeah, watch is way better with incremental support... but the compiler supports incremental builds, so the only full rebuild each time is what TypeDoc does. This can still be significant time savings on large TS projects.

https://github.com/TypeStrong/typedoc/pull/1482 adds support for watch.

**Closed** 2021-01-25 14:45 UTC
Labels: enhancement
