### ISSUE TITLE
The type defined on the type does not take effect

### ISSUE THREAD

**Issue by rxliuli** [TypeStrong/typedoc#1038] opened 2019-05-24 01:13 UTC
I used type to define a type, but even if I added a comment, I can't find the corresponding content in the generated document. Is my annotation wrong? How can I use it?

![image](https://user-images.githubusercontent.com/24560368/58295909-f0b66e00-7e03-11e9-9a16-c3860a08db12.png)

Source

```ts
/**
 * 提供者函数，用于生成任意值的函数
 * @typeparam R 返回结果类型
 * @returns 返回结果
 */
export type Supplier<R> = () => R
```

Sorry, I can't provide an online example at this time. . .

**Comment by Gerrit0** [comment] 2019-10-14 03:07
Duplicate of #983

**Closed by Gerrit0** 2019-10-14 03:07 UTC
Labels: bug
