### ISSUE TITLE
question - how to make search.js smaller

### ISSUE THREAD

**Issue by lab4quant** [TypeStrong/typedoc#747] opened 2018-04-11 07:03 UTC
Hello, I'm working on a large typescript project, with 1000+ source file

The generated `search.js` file is 20M+. I tried using module plugin, which reduced `search.js` to 8M+

But still it's very slow when click search button, and it needs to load and run `search.js` every time I navigate to other page.

Is there anyway to make search.js file smaller, or even exclude contact to be in the search?

thanks!

**Comment by aciccarello** [comment] 2018-04-11 13:49
Thanks for reporting, but this seems like a duplicate of #739. The search functionality probably needs to be reworked. I'll close this in favor of the other issue.

**Closed by aciccarello** 2018-04-11 13:49 UTC
