### ISSUE TITLE
Type intersection details not rendered

### ISSUE THREAD

**Issue by mistic100** [TypeStrong/typedoc#1765] opened 2021-10-25 21:41 UTC
## Expected Behavior

I have the following types :

```typescript
/**
 * Object defining a spherical position
 */
export type Position = {
  longitude: number;
  latitude: number;
};

/**
 * Object defining panorama and animation options
 */
export type PanoramaOptions = Partial<Position> & {
  /**
   * new zoom level between 0 and 100
   */
  zoom?: number;
  /**
   * duration of the transition between all and new panorama
   */
  transition?: boolean | number;
  /**
   * show the loader while loading the new panorama
   * @default true
   */
  showLoader?: boolean;
};
```

I expect the PanoramaOptions to at least list its three additional properties.

![expected](https://user-images.githubusercontent.com/41597/138774743-238d1565-50f8-4967-beca-3de2219b1409.PNG)

## Actual Behavior

Instead absolutely no detail is rendered.

![actual](https://user-images.githubusercontent.com/41597/138774792-b0fc66b9-1490-4ef2-9f0b-d2ec4482e547.PNG)

The same behavior is observed with `Position & { ... }` (supposing `Partial` throws the parser off) or with an union type `Position | { ... }`

If that matters I am parsing ".d.ts" files, not typescript source.

## Environment

-   Typedoc version: 0.22.7
-   TypeScript version: 4
-   Node.js version: 14.17
-   OS: W10

**Comment by Gerrit0** [comment] 2021-11-01 01:12
Duplicate of #1519, something I want to do, but haven't gotten around to implementing yet

**Closed by Gerrit0** 2021-11-01 01:12 UTC
Labels: duplicate, enhancement
