### ISSUE TITLE
TypeError: Cannot read property 'setFlag' of null

### ISSUE THREAD

**Issue by EvanDarwin** [TypeStrong/typedoc#691] opened 2018-02-01 16:54 UTC
Hi there,

I'm encountering this error on W10, on my first run of TypeDoc v0.10.0. Tried on both Node 9.5.0 and 8.9.3.

```
PS C:\...\MyProj> yarn docs
yarn run v1.3.2
$ typedoc --excludePrivate --excludeNotExported --out docs/ src/

Using TypeScript 2.7.1 from C:\...\MyProj\node_modules\typedoc\node_modules\typescript\lib
C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\variable.js:74
                    variable.setFlag(index_1.ReflectionFlag.Const, true);
                             ^

TypeError: Cannot read property 'setFlag' of null
    at VariableConverter.convert (C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\variable.js:74:30)
    at Converter.convertNode (C:\...\MyProj\node_modules\typedoc\dist\lib\converter\converter.js:127:53)
    at C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\variable-statement.js:39:33
    at Array.forEach (<anonymous>)
    at VariableStatementConverter.convert (C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\variable-statement.js:34:47)
    at Converter.convertNode (C:\...\MyProj\node_modules\typedoc\dist\lib\converter\converter.js:127:53)
    at C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\block.js:85:29
    at Array.forEach (<anonymous>)
    at BlockConverter.convertStatements (C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\block.js:84:26)
    at C:\...\MyProj\node_modules\typedoc\dist\lib\converter\nodes\block.js:62:27
```

**Comment by aciccarello** [comment] 2018-02-01 17:37
Hello, that looks like it may have been caused by #611. Do you have a small amount of code that can reproduce this error. Are you using `const` anywhere other than for variable declaration?

**Comment by EvanDarwin** [comment] 2018-02-01 18:03
I'm not sure what code that I have that would trigger this, the codebase is pretty simple and it lints just fine. I don't think I have any special or weird uses of `const`. I'm also encountering this issue in WSL (Ubuntu on Windows).

**Comment by aciccarello** [comment] 2018-02-01 18:44
I'm not able to reproduce the error. Do you have a small repo demonstrating the issue that you could share?

![const variable documentation screenshot](https://user-images.githubusercontent.com/11273838/35696577-1aee0624-0745-11e8-8f43-c19d1e0af987.png)

**Comment by EvanDarwin** [comment] 2018-02-01 21:09
@aciccarello I'm not sure where the issue even exists as it's my first time running it in this project. It's not exactly a small codebase but I'm in the process of trying to publish it publicly on GitHub.

**Comment by EvanDarwin** [comment] 2018-02-01 23:35
@aciccarello I've narrowed the cause of the error down. 

The issue occurs when trying to `require()` a dependency that's not installed (for example, a peer dependency) WHILE using the `--excludeNotExported` argument.

The following file will throw the setFlag() error:
```js
const localForage = require('localforage');
```

**Comment by aciccarello** [comment] 2018-02-02 01:09
Ah, the exclude exported flag appears to be the cause. Creating a const variable without exporting it and using the `--excludeNotExported` flag reproduces it. I don't think the `require()` call is significant.

**Comment by aciccarello** [comment] 2018-02-02 04:41
Closed via #694

**Comment by blutorange** [comment] 2018-02-04 21:26
This is still happening for me with the latest version (and TypeScript 2.7.1), but I managed to narrow it down to the following simple case.

Code
```typescript
abstract class BaseTryImpl {
}
```
I run

```sh
 ../typedoc/bin/typedoc --mode file --out doctest --excludeNotExported test.ts
```

which results in
```
Using TypeScript 2.7.1 from /home/mad_gaksha/Applications/typedoc/node_modules/typescript/lib
/home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/class.js:43
                reflection.setFlag(index_1.ReflectionFlag.Abstract, true);
                           ^

TypeError: Cannot read property 'setFlag' of null
    at ClassConverter.convert (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/class.js:43:28)
    at Converter.convertNode (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/converter.js:127:53)
    at /home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/block.js:78:33
    at Array.forEach (<anonymous>)
    at BlockConverter.convertStatements (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/block.js:76:29)
    at /home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/block.js:67:23
    at Context.withSourceFile (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/context.js:87:9)
    at BlockConverter.convertSourceFile (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/block.js:58:17)
    at BlockConverter.convert (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/nodes/block.js:48:18)
    at Converter.convertNode (/home/mad_gaksha/Applications/typedoc/dist/lib/converter/converter.js:127:53)
```

It works once I remove the `--excludeNotExported` flag, or the `abstract` modifier from the class.

**Comment by aciccarello** [comment] 2018-02-04 21:57
@blutorange Thanks for investigating. A fix has been merged into master but I still need to make a release after testing another bug fix.

**Comment by blutorange** [comment] 2018-02-05 05:33
@aciccarello Thanks for replying so quickly. Do you mean the fix mentioned above (#694)? I cloned this repository and tried it with a fresh build of that. It only seems to be fixing a null variable in file `variable.js`, whereas with the example I tried there is a null variable in file `class.js`.

**Comment by aciccarello** [comment] 2018-02-05 16:58
@blutorange Ah, I missed that it was showing up in a different class. I'm curious if there is a problem with the `createReflection` method.

**Comment by aciccarello** [comment] 2018-03-01 06:27
So `createReflection` should be expected to sometimes be null. Therefore we should add a check of the result in [`class.ts`](https://github.com/TypeStrong/typedoc/blob/32bf5289fc7742c6c2e80b786b298987e5336aaa/src/lib/converter/nodes/class.ts#L34). The [other instances](https://github.com/TypeStrong/typedoc/search?p=1&q=createDeclaration&type=&utf8=%E2%9C%93) should be fine. Any uses in `context.withScope(reflection, ...)` are fine because `withScope` checks if the scope exists. The few other cases are already handled.

I'm surprised this hasn't been identified before but the fix should be simple.

**Closed** 2018-03-05 05:31 UTC
Labels: Priority: 1, bug, help wanted
