### ISSUE TITLE
Missing canonical link in the default theme

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2550] opened 2024-04-16 21:01 UTC
## Search terms

default theme, canonical link

## Expected Behavior

Index page generated by typedoc should include a [rel canonical link](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method).

## Actual Behavior

Index page generated with the default theme does not have it.

## Explanation

A rel canonical link informs a search engines that which page is the canonical page, i.e., the page that users should use. For example, the following two URLs have the exactly the same content:

- https://typedoc.org/api/
- https://typedoc.org/api/index.html

A user can read the content by visiting either the of the URLs above. However, it is better for search engine to only index one of them so that the search results would be consistent and avoids content duplication in search results (while Search Engines also do some guesswork, they are not reliable and would punish the websites that do not mark canonical pages properly). By including a rel canonical link in the index page, search engines would understand the relationship between the two pages:

```
<link rel=canonical href=${sitemapBaseUrl}/>
```

The link does not have any effects to human visitors; they are only there for search engines.

(I'm getting a ton of warnings from Google Search Console)

**Comment by Gerrit0** [comment] 2024-04-19 00:14
This should probably only be emitted if sitemapBaseUrl is set, since otherwise it'd result in a lie... it feels off to me to use this option for emitting that, but it's not necessarily wrong... just weird...

According to that Google page, it sounds like the sitemap should also include `base/` rather than `base/index.html` as it currently does for the page index.

If doing this... we probably ought to also add a check to handle pages which render as `index.html` in the modules/functions/classes directories. In their case, the `/` really ought *not* be the canonical URL, as they aren't a landing page for the directory, but caused by an exported thing named `index`... maybe that should actually be a special case where it's renamed to `index.namespace.html` or something...

**Comment by xuhdev** [comment] 2024-04-19 00:24
Maybe we can rename `sitemapBaseUrl` to `publicHostingBaseUrl`? There are probably more unknown optimizations for public hosting that are not done...

**Comment by Gerrit0** [comment] 2024-04-27 19:02
I think `hostedBaseUrl` is reasonable, can't happen until the next minor release though

**Comment by Gerrit0** [comment] 2024-06-16 21:33
Fixed with TypeDoc 0.26, which is releasing 2024/06/21

**Closed by Gerrit0** 2024-06-16 21:33 UTC
Labels: bug
