### ISSUE TITLE
Don't list @types packages as dependencies

### ISSUE THREAD

**Issue by zelein** [TypeStrong/typedoc#600] opened 2017-09-27 15:03 UTC
I tried installing typedoc and am suddenly getting a build error for a type definition that I don't even depend on, but typedoc does.

```
export function highlightBlock(block: Node) : 
node_modules/@types/highlight.js/index.d.ts(19,40): error TS2304: Cannot find name 'Node'.
```

All `@types` dependencies should be moved to `devDependencies` in `package.json`

**Comment by aciccarello** [comment] 2017-09-27 15:15
Duplicate of #408 #335 #350 #384 #418 and #434

Please see those issues for discussion. **TLDR:** It isn't ideal but we need to have it that way.

When #579 is released that might fix your issue.

**Closed by aciccarello** 2017-09-27 15:15 UTC

**Comment by zelein** [comment] 2017-09-27 15:19
Thanks aciccarello.

This doesn't really fix my issue though. What types am I missing that is causing this to fail?

**Comment by aciccarello** [comment] 2017-09-27 15:29
These errors usually happen because the type definition files are updated but don't follow semantic versioning so the version npm resolves is not compatible with the one used when TypeDoc was released. That's why #579 is pinning the versions.

As a workaround, you can use the `--ignoreCompilerErrors` option to get TypeDoc to build.

**Comment by zelein** [comment] 2017-09-27 15:32
Makes sense.

Thanks, will try that flag.
