### ISSUE TITLE
Why does TypeDoc think all modules are missing? (Error: Could not find a declaration file for module)

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/typedoc#1089] opened 2019-08-11 05:23 UTC
I'm not having luck with generating TypeScript docs. I've been trying various tools, including TypeDoc, but no luck so far.

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

I have a project that compiles fine with `tsc`, `gulp-typescript` and `webpack`.

I am hoping to be able to run something like

```
typedoc --out ./typedocs --mode modules --excludeExternals --excludeNotExported --excludePrivate --excludeProtected ../infamous+infamous/src/index.ts
```

and get generated docs.

## Actual Behavior

I get a bunch of errors like

```
...
Error: /Users/trusktr/src/infamous+infamous/src/lib/jss/index.ts(2)
 Could not find a declaration file for module 'jss-nested'. '/Users/trusktr/src/infamous+infamous/node_modules/jss-nested/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/jss-nested` if it exists or add a new declaration (.d.ts) file containing `declare module 'jss-nested';`
Error: /Users/trusktr/src/infamous+infamous/src/lib/jss/index.ts(3)
 Could not find a declaration file for module 'jss-extend'. '/Users/trusktr/src/infamous+infamous/node_modules/jss-extend/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/jss-extend` if it exists or add a new declaration (.d.ts) file containing `declare module 'jss-extend';`
...
```

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: 12.7.0
  - OS: macOS

**Comment by trusktr** [comment] 2019-08-11 05:27
## Steps to reproduce the bug

Clone https://github.com/infamous/infamous, checkout the branch `TypeStrong/typedoc-issue-1089`, install dependencies, then `npm run typedoc`.

That should give the errors.

**Comment by Gerrit0** [comment] 2019-08-11 16:11
Geez, I think that's the first time I've cloned something that took longer than the TypeScript repo to install dependencies... 

---

Notes while debugging:
- You are using a ridiculously old version of `jss`. Installing with `yarn` errors as it expects node <6.0.0.
- Installed successfully with `npm i`,
- I see the errors, after renaming the cloned repo folder to `infamous+infamous`. Why does the package assume I'm installing in a specific folder name, especially one that isn't the default when just doing a `git clone`?
- The tsconfig.json uses `extends`, I know this caused problems for TypeDoc in the past, and I don't recall it being fixed, looking at [utils/options/readers/tsconfig.ts](https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/tsconfig.ts) doesn't immediately tell me if it was fixed.
- Tried copying the extended tsconfig.json file into the root tsconfig.json, confirmed `npm run build` still worked (after correcting paths). This got rid of *most* of the TypeDoc errors, so it looks like TypeDoc still can't handle `extends`. #380 was potentially closed prematurely.
- The remaining errors are caused by TypeDoc not picking up `src/types/global.d.ts`. This is likely caused by `Application#expandInputFiles` not finding `global.d.ts` as TypeDoc currently does not use TypeScript to find all source files. If the input files are changed from `../infamous+infamous/src/index.ts` to `../infamous+infamous/src/` TypeDoc will recurse through the directories and correctly pick up `global.d.ts`.
- `npm run typedoc` works.

---

Looks like there are a couple issues:
1. TypeDoc should be able to use the `include` option in `tsconfig.json` to resolve source files.
1. TypeDoc doesn't support `extends` in `tsconfig.json`

**Comment by aciccarello** [comment] 2019-08-14 17:41
@trusktr Thanks for posting the issue and describing how to reproduce. We'll need to review the tsconfig options. Include was marked as being supported in #359 but it may not be. I've also reopened #380.

**Comment by Neloreck** [comment] 2019-09-13 11:50
@trusktr
I was able to generate docs after modifying your script:

```
        "typedoc": "typedoc --out ./typedocs --exclude **/node_modules/** --mode modules --excludeExternals --excludeNotExported --excludePrivate --excludeProtected ./src",
```

1) You declared target script, not folder
2) Not all modules have typedefs and not all modules have right typedefs, so better exclude **/node_modules/**

Hope, answer is not too late :)

**Comment by Gerrit0** [comment] 2020-12-29 00:18
> Looks like there are a couple issues:
> TypeDoc should be able to use the include option in tsconfig.json to resolve source files.
> TypeDoc doesn't support extends in tsconfig.json

**Closed** 2020-12-29 00:19 UTC
Labels: bug

**Comment by AndyOGo** [comment] 2021-01-02 11:47
I just upgraded to `0.20.9` - PR here https://github.com/AndyOGo/stylelint-declaration-strict-value/pull/131

However I still can't build the docs.
It doesn't find my custom declaration files for 2 modules.

But my normal lint and build with typescript works.
