### ISSUE TITLE
exclude not exported not working with version 0.16.10

### ISSUE THREAD

**Issue by euberdeveloper** [TypeStrong/typedoc#1219] opened 2020-02-26 15:43 UTC
- [ ] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

I updated my project with typescript on version 0.16.10 of typedoc. I am using --mode file
I expected the library to work as with the previous version, so purging all helper functions that are not exported.

## Actual Behavior

The problem is that now --excludeNotExported is not working any more and everything is included in the output.

## Steps to reproduce the bug

To reproduce this bug, just run `typedoc --out docs/html --mode file --plugin none --excludeNotExported --includeVersion --gaID $GA_TOKEN source/lib` on a project with exported and not exported functions

## Environment
  - Typedoc version: 0.16.10
  - Node.js version: 12.14.1
  - OS: ubuntu 18.04

**Comment by Gerrit0** [comment] 2020-02-26 17:08
Duplicate of #1195 

This is expected behavior with `--mode file`. In file mode you are telling TypeDoc to ignore that you are actually using modules and pretend everything is global.

**Closed by Gerrit0** 2020-02-26 17:08 UTC
Labels: duplicate, no bug
