### ISSUE TITLE
Could Typedoc just parse the items exported from index.d.ts

### ISSUE THREAD

**Issue by angelwen08** [TypeStrong/typedoc#1033] opened 2019-05-07 03:56 UTC
When we are using typedoc to generate json/html output, sometimes we want typedoc just output the items exported in a file like index.d.ts.  The file will looks like:
...
export { Sender } from "./sender";
export { Receiver, SessionReceiver } from "./receiver";
export { MessageHandlerOptions } from "./core/streamingReceiver";
export { OnError, OnMessage } from "./core/messageReceiver";
...

    But currently it output nothing if we just provide the index.d.ts.  but if we provide the directory contains the index.d.ts, everything in this directory will get output

Steps to reproduce the bug:

1. npm install @azure/service-bus
2. typedoc --json api.json typings/src/index.d.ts --module commonjs --includeDeclarations --ignoreCompilerErrors --excludeExternals

or typedoc --json api.json typings/src --module commonjs --includeDeclarations --ignoreCompilerErrors --excludeExternals

Environment
  - Typedoc version: 0.12.0
  - Node.js version: 10.15.3
  - OS: windows 10

**Comment by Gerrit0** [comment] 2019-05-07 04:10
Duplicate of #639 - it's on the list, but hasn't been implemented yet.

**Closed by Gerrit0** 2019-05-07 04:10 UTC
Labels: bug
