### ISSUE TITLE
"Implementation of X.y" does not work correctly for `Iterable<T>`

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#2234] opened 2023-04-10 11:51 UTC
## Search terms

iterable, implementation of

## Expected Behavior

When a class implements an interface `Foo` that extends `Iterable<T>`, then the class method should have a note: "Implementation of "Implementation of Foo.[iterator]" or "Foo[iterator]".

## Actual Behavior

![image](https://user-images.githubusercontent.com/20878432/230895945-34c0cd5a-c058-4d77-b3eb-aaf46f21af29.png)

This is likely caused by typedoc not generating an inherited method for `ReadonlyCharMap[iterator]`.

## Steps to reproduce the bug

1. Download https://github.com/RunDevelopment/refa
2. `npm ci`
3. `npm i -d typedoc@0.24.1`
4. `npm run build:docs`
5. Open `docs/index.html`

Or see the doc pages generated by 0.23.28: [`CharMap[iterator]`](https://rundevelopment.github.io/refa/docs/v0.11.0/classes/CharMap.html#_iterator_)

## Environment

-   Typedoc version: 0.24.1 (or 0.23.x)
-   TypeScript version: 5.0.2
-   Node.js version: 16.13.0
-   OS: Win10

**Comment by Gerrit0** [comment] 2023-04-15 21:21
https://github.com/RunDevelopment/refa/blob/c2072a17306c73593e06a9bdfa61ef67471f4ca2/src/char-map.ts#L523

**Comment by Gerrit0** [comment] 2023-04-15 21:36
This is mostly working as intended. `ReadonlyCharMap` doesn't get an `[iterator]` property because it is considered external as all declarations are in node_modules and TypeDoc [is configured](https://github.com/RunDevelopment/refa/blob/master/typedoc.json#L3) to exclude externals.

TypeDoc should be resolving `__@iterator` to `[iterator]` though in the excluded externals case, so that needs to be fixed.

**Closed** 2023-04-15 21:39 UTC
Labels: bug
