### ISSUE TITLE
Documents on "http://typedoc.org/" are outdated.

### ISSUE THREAD

**Issue by lord-saumagen** [TypeStrong/typedoc#296] opened 2016-09-21 18:55 UTC
The document on "http://typedoc.org/" are outdated. The link to the "api documentation" does not work.
![apidocumentation](https://cloud.githubusercontent.com/assets/9468599/18724738/c36cd86a-803d-11e6-847d-e0cd8c1ef0a4.png)

**Comment by blakeembrey** [comment] 2016-09-21 19:48
Duplicate of https://github.com/TypeStrong/typedoc/issues/294.

**Closed by blakeembrey** 2016-09-21 19:48 UTC
