### ISSUE TITLE
The "Inherited", "Externals", and "Only exported" buttons do not do anything.

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/typedoc#1065] opened 2019-07-05 01:41 UTC
## Expected Behavior

Expecting those buttons to filter the content.

## Actual Behavior

For example, after enabling "Only exported", I still see everything.

## Steps to reproduce the bug

Link the latest version from GitHub into your project, and you'll get both the [lunr error](https://github.com/TypeStrong/typedoc/issues/1058), and the buttons don't do appear to do anything.

## Environment
  - Typedoc version: dfb7207383bdd6a9b7e69271b18bb154b6fec7d9 (master at time of writing)
  - Node.js version: 11.14
  - OS: macOS

**Comment by Gerrit0** [comment] 2019-07-05 17:33
I suspect the lunr error is preventing the event listener being added to handle the changes. Running with the latest changes in the themes I was able to confirm that the "Inherited" and "Only exported" checkboxes work. My test case (the TypeDoc code) doesn't actually have any "External" elements documented, so I wasn't able to check that.

**Comment by Gerrit0** [comment] 2019-11-14 18:52
Closing, I can't reproduce in 0.15.2, the lunr error was fixed in 0.15.1.

**Closed by Gerrit0** 2019-11-14 18:52 UTC
Labels: bug
