### ISSUE TITLE
Documentation error: angle/square brackets for internal linking

### ISSUE THREAD

**Issue by jesperstarkar** [TypeStrong/typedoc#253] opened 2016-07-09 08:33 UTC
[The documentation](http://typedoc.io/guides/doccomments.html) says 
`Additionally you can link to other classes, members or functions using double angle brackets.`

where it should have said

`Additionally you can link to other classes, members or functions using double brackets.`

alternatively

`Additionally you can link to other classes, members or functions using double square brackets.`

**Comment by aciccarello** [comment] 2016-07-11 12:29
+1 to the "square brackets" version

**Comment by blakeembrey** [comment] 2016-07-12 18:24
Closing as a duplicate of https://github.com/TypeStrong/typedoc/issues/79. I don't believe I have access to update the docs directly, but if you find something let me know.

**Closed by blakeembrey** 2016-07-12 18:24 UTC
