### ISSUE TITLE
reexport variable would be treat as external variable

### ISSUE THREAD

**Issue by XGHeaven** [TypeStrong/typedoc#686] opened 2018-01-24 14:58 UTC
File Folder
- cwd
  - index.ts
  - types.ts

```typescript
// types.ts
export class A {}
export enum B {}
export interface C {}
export function D {}
```

```typescript
// index.ts
import {A, B, C, D} from './types'
D() // do some action
export {A, B, C}
```

Run generate docs command

```shell
typedoc --out docs --mode file index.ts
```

I expect `class A` & `enum B` & `interface C` are internal variable and shown in doc.
And `function D` don't shown in docs.

But the fact is `class A` `enum B` `interface C` `function D` are shown in doc as external variable.

**Comment by aciccarello** [comment] 2018-02-01 07:21
Yeah, currently TypeDoc doesn't really care about what is exported and what isn't. I agree there should be work done on this but will close this as a duplicate of #639

**Closed by aciccarello** 2018-02-01 07:21 UTC
