### ISSUE TITLE
TypeError: ts.isIdentifierOrPrivateIdentifier is not a function

### ISSUE THREAD

**Issue by serge-hulne** [TypeStrong/typedoc#1387] opened 2020-10-31 11:42 UTC
```
$ tsc -v
Version 3.2.2

TypeDoc 0.19.2
Using TypeScript 3.2.2 from C:\Users\serge\AppData\Roaming\npm\node_modules\typescript\lib
```

test carried out:

```
 typedoc --out docs ./axino
```

Were axino is a directory containing ts souce code:
```
$ ls axino/
button.ts  channel.ts   constants.ts  div.ts     examples-electron-1/  index.html  label.ts  list.ts        olist.ts      radio.ts   select.ts  testing.ts
canvas.ts  checkbox.ts  core.ts       examples/  form.ts               input.ts    LICENSE   markdown.html  package.json  README.md  table.ts   textarea.ts
```

Error message :
```
C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:195
    return node['name'] && (ts.isIdentifierOrPrivateIdentifier(node['name']) ||
                               ^

TypeError: ts.isIdentifierOrPrivateIdentifier is not a function
    at isNamedNode (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:195:32)
    at Context.getSymbolAtLocation (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\context.js:48:24)
    at Object.createDeclaration (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\factories\declaration.js:80:32)
    at VariableConverter.convert (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\variable.js:59:34)
    at Converter.convertNode (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\converter.js:117:53)
    at node.declarationList.declarations.forEach (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\variable-statement.js:26:32)
    at Array.forEach (<anonymous>)
    at VariableStatementConverter.convert (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\variable-statement.js:21:47)
    at Converter.convertNode (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\converter.js:117:53)
    at statements.forEach (C:\Users\serge\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\nodes\block.js:66:28)
```

**Comment by Gerrit0** [comment] 2020-10-31 14:48
Duplicate of #1257. You're running on an unsupported version of TypeScript. The supported versions for 0.19 are 4.0.x and 3.9.x.

In addition to the warning #1257 talks about, 0.19.2 also warns when you run TypeDoc.

**Comment by serge-hulne** [comment] 2020-10-31 15:04
Thank you very much!

Congratulations for TypeDoc !
and all my apologies :-)

**Closed** 2020-10-31 15:09 UTC
Labels: bug
