### ISSUE TITLE
Implementation of additional MD files

### ISSUE THREAD

**Issue by Voo2** [TypeStrong/typedoc#2365] opened 2023-08-16 07:11 UTC
## Search Terms

Markdown, additional documentation, include

## Problem

I would like to see TypeDoc offers the possibility to include additional MarkDown documents.

## Suggested Solution

I find the way Compodoc solves it ideal. There, the files that have the same name as the component, but with the md file extension, are simply included as a separate tab.

Here is an example in an Angular project:

--example.component.ts
--example.component.scss
--example.component.html
--**example.component.md**

In this example, typedoc would recognise that an md file exists for this component, which should be included. In order to access this document, typedoc then creates a tab on the doc page for the component, with which one can switch to this additional documentation.

Of course, this can also be done in another way, e.g. by simply adding a section to the doc page of the component where the additional page is located.

**Comment by Gerrit0** [comment] 2023-08-16 12:38
Duplicate of #247, something I want to do at some point when I have a couple weeks to work on typedoc again

**Closed** 2023-08-19 15:17 UTC
Labels: duplicate, enhancement

**Comment by Voo2** [comment] 2023-08-19 17:15
Good question. In #247 it is not apparent to me. Does that mean you no longer want to do this?

**Comment by Gerrit0** [comment] 2023-08-19 20:14
Inclusion of markdown support documents as a feature in general is tracked by 247, I don't feel the need to track it in multiple issues. The design I have in mind will support both the "here's a folder of docs" and "here's supplemental docs" use cases.
