### ISSUE TITLE
@category appears under function type aliases (only) with typedoc 0.22.6

### ISSUE THREAD

**Issue by KillyMXI** [TypeStrong/typedoc#1745] opened 2021-10-19 18:34 UTC
## Search terms

Function type aliases, comment tags, category.

## Expected Behavior

`@category` tag behavior is consistent across different entities. In particular, it's visibility in the documentation is governed by the same rule.

Prior to 0.22.6 it was properly used to categorize documentation entities and was not shown under any of them and that makes total sense for me.

## Actual Behavior

Version 0.22.6 still uses it to categorize documentation entities, but also started to include it under function type aliases specifically (other type aliases and functions are unaffected by the change and no `@category` tag is shown for them).

Apparently this is caused by #1734 and 0d04c08

I see no sense to clutter the docs with this specific tag since it is used for grouping already.
If there is a good reason to show it then there should be clean rules and a way to override them.
Current behavior is very surprising.

## Steps to reproduce the bug

Version 0.22.6 (0.22.5 is fine)

Code like this:

```ts
/**
 * Foo...
 *
 * @param data - Data...
 *
 * @category My category
 */
export type Foo<T,R> = (data: T) => R;
```

Typedoc options:

```json
  "typedocOptions": {
    "categorizeByGroup": false,
    "categoryOrder": [
      "My category",
      "..."
    ],
    "customCss": "./assets/docs.css",
    "defaultCategory": "...",
    "disableSources": true,
    "entryPoints": [
      "src/foo.ts",
      "src/bar.ts"
    ],
    "includeVersion": true,
    "out": "docs",
    "sort": "alphabetical"
  },
```

## Environment

-   Typedoc version: 0.22.6
-   TypeScript version: 4.4.4
-   Node.js version: 12.21.0
-   OS: Windows 10

**Comment by Gerrit0** [comment] 2021-10-22 02:50
Fixed in https://github.com/TypeStrong/typedoc/commit/abc6263238fda4619ce7e4bf8662ff1abf559461

**Comment by Gerrit0** [comment] 2021-10-31 15:44
Yep... I'm seeing that too now, weird.

**Closed** 2021-10-31 15:53 UTC
Labels: bug

**Comment by Gerrit0** [comment] 2022-05-30 21:01
This bug wins the prize for being the thing I've accidentally broken the most in the past 6 months, then run the tests, noticed, fixed, and broken literally the next time I touched the category code. Sheesh!

**Comment by LennardF1989** [comment] 2023-08-21 00:30
@Gerrit0 I think it's back again in 0.24.8 (and maybe before?).

Here is my test-case:

```
/** 
 * Type definition of function used to resolve a promise
 * 
 * @param value Test
 */
export type PromiseResolve = 
/** 
 * Type definition of function used to resolve a promise
 * 
 * @param value Test 1
 */
export type PromiseResolve = 
    /**
     * Lambda
     * 
     * @param value Test 2
     */
    (value: any) => void;
```

The description is not show as part of the type (like would happen for a simple `export type ApiFailReason = string;`), but rather for the lambda itself. The param of `value` will show `Test 1`. I'm not even sure this is valid syntax...

![image](https://github.com/TypeStrong/typedoc/assets/869973/a1fb6c1d-d656-45bd-8ccf-33c90396e47d)

![image](https://github.com/TypeStrong/typedoc/assets/869973/218f479d-a701-4cf6-b39e-475eb2c4688f)

**Comment by Gerrit0** [comment] 2023-08-25 19:28
That would be a duplicate of #2372, but please open a new issue in general. I don't like pinging people for very old resolved issues
