### ISSUE TITLE
Links no longer work with 0.23 and print a warning instead

### ISSUE THREAD

**Issue by B4nan** [TypeStrong/typedoc#2000] opened 2022-07-13 09:39 UTC
## Search terms

Failed to resolve ... with declaration references. This link will break in v0.24.

## Expected Behavior

Some links stopped working with latest update (maybe all of them, haven't seen a single one working yet). Those are valid links to symbols that are part of the generated API docs, so its definitely not about pointing to something not exported.

## Actual Behavior

Warning is printed when building the docs in this form:

```
warning Failed to resolve {@link BatchAddRequestsResult} in core/src.enqueueLinks with declaration references. This link will break in v0.24.
```

Also note that links that are in form of `{@link something|else}` will print a warning as "failed to resolve {@link else}" which sounds like a separate bug to me as well. I would also suggest adding a line number so its easier to understand which line caused the warning.

## Steps to reproduce the bug

Here is a PR to our docs with docusaurus update, typedoc update is part of the transitive dependencies. 

https://github.com/apify/apify-ts/pull/181

If you'd like to run this yourself, clone the repository, install deps in root, `cd website`, install deps there and run `npm start`. As part of the website bootstrap, typedoc is used to generate the JSON definition file that is used by a docusaurus plugin to generate the API docs. 

Typedoc config is part of the docusaurus one here:

https://github.com/apify/apify-ts/blob/update-docusaurus/website/docusaurus.config.js#L55-L93

The links before the update (in master branch) are working just fine, with this upgrade they break and a warning is printed as mentioned above. One concrete example we can talk about is https://crawlee.dev/api/core/function/enqueueLinks (method definition is [here](https://github.com/apify/apify-ts/blob/master/packages/core/src/enqueue_links/enqueue_links.ts#L166)), you can see that on this link there are 3 `@link` tags used, and correctly rendered. While after upgrade, warning is printed in the logs and links are not rendered (just as a plain text). In this particular example, the link to `RequestQueue` and `Request` classes are both targetting classes from the very same package - looks like those two did not print a warning at all but they are not rendered either. The `BatchAddRequestsResult` link produced a `warning Failed to resolve {@link BatchAddRequestsResult} in core/src.enqueueLinks with declaration references. This link will break in v0.24.`.

_I am filing the issue here, as I believe the problem is coming from typedoc, but the reproduction is using docusaurus with https://github.com/milesj/docusaurus-plugin-typedoc-api_

## Environment

-   Typedoc version: 0.23
-   TypeScript version: 4.6.4, works same with 4.7.4
-   Node.js version: 18.5, works same in other versions too
-   OS: macos, ubuntu

**Comment by B4nan** [comment] 2022-07-13 09:41
cc @milesj

**Comment by tomfrenken** [comment] 2022-07-13 14:14
Possibly related to #1995

**Comment by Gerrit0** [comment] 2022-07-17 21:59
It sounds like you were relying on step 4 [described here](https://typedoc.org/guides/link-resolution/), which searches for names in a global list of all reflections. Declaration references don't work like that, they require a name which specifies other scopes if traversing into them: https://typedoc.org/guides/declaration-references/

Guessing based on your API site, `{@link @crawlee/types!BatchAddRequestsResult}` should do what you want for the cross-package link. For `Request` and `RequestQueue`, I'd expect the same link to still work.... that project is too big for me to spend time getting set up to try to reproduce a bug, if there is one. If you can create a minimal repro, I can look into that. (This might be playing badly with plugins, I'd want to see it not work with the default theme)

**Comment by B4nan** [comment] 2022-07-18 10:14
I can understand the `BatchAddRequestsResult` one, but I failed to understand why you call this "no bug" when the other two should be clearly working. This is very basic monorepo setup, no plugins used, we use typedoc to only generate the JSON definition. 

I will try to provide minimal repro.

> (This might be playing badly with plugins, I'd want to see it not work with the default theme)

This report is about the JSON definitions exported from typedoc, we dont use typedoc to render anything.

**Comment by B4nan** [comment] 2022-07-19 23:09
Tried to debug this a bit, and I believe the problem is actually in the docusaurus plugin I am using, so sorry for the noise, closing. Looks like the JSON definition has changed in 0.23. Previosly the link macros were there intact, now they are provided as separate items in summary array.

with 0.22:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/615580/179863206-011ac825-6311-4d90-83c5-04bc4cdf372e.png">

and with 0.23:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/615580/179863106-8c8a8a93-35f3-4954-9feb-ecb174415145.png">

Btw regarding the warnings for cross package links, maybe we could respect what is imported in the file? Like the `BatchAddRequestsResult` interface is imported in the file where I use the `{@link BatchAddRequestsResult}` in the comment. I can understand the need for fully qualified path when its not imported, but this feels a bit weird.

**Comment by B4nan** [comment] 2022-07-20 19:31
The suggested way to get around the warning does not seem to be working. Tried to change the link but I am still getting the same warning:

```
warning Failed to resolve {@link @crawlee/types!BatchAddRequestsResult} in core/src.enqueueLinks with declaration references. This link will break in v0.24.
```

**Comment by Gerrit0** [comment] 2022-07-23 20:57
I'm going to have to ask for a minimal reproduction, I don't have time to investigate with really large projects. https://github.com/TypeStrong/typedoc-repros has a minimal setup to start with.

**Comment by ksstoneware** [comment] 2022-08-03 20:08
@Gerrit0  I don't know if it's related, but I was able to see this issue with exported functions. For instance, this works fine without a warning:
```
/**
 * Do stuff.
 *
 * @throws {@link Error} just because.
 */
function throwError(): void {
    throw new Error("Hi");
}
```

If I export the function, I now get link warnings:
```
/**
 * Do stuff.
 *
 * @throws {@link Error} just because.
 */
export function throwError(): void {
    throw new Error("Hi");
}

warning Failed to resolve {@link Error} in throwError with declaration references. This link will break in v0.24.
warning Failed to resolve link to "Error" in comment for throwError.throwError
```
It's breaking a lot of stuff for us since updating 0.23.x. We are currently using 0.23.8.

**Comment by Gerrit0** [comment] 2022-08-06 13:15
@ksstoneware that looks expected to me. TypeDoc doesn't do anything with code that isn't exported, so if you just made a function exported, TypeDoc will only now start parsing its comment.

Unless you export an `Error` class, this won't work. TypeDoc doesn't resolve links to types unless included in your documentation.

These links were likely broken in earlier versions of TypeDoc as well, but they weren't reported because `--validation.invalidLink` defaulted to false before 0.23.

If you think the link should be resolved according to <https://typedoc.org/guides/declaration-references/>, please open a new issue, closing this one as can't repro.

**Closed by Gerrit0** 2022-08-06 13:15 UTC
Labels: bug, needs reproduction
