### ISSUE TITLE
@deprecated tag

### ISSUE THREAD

**Issue by thernstig** [TypeStrong/typedoc#1531] opened 2021-03-10 07:55 UTC
## Search Terms

`@deprecated`, jsdoc, typedoc, vs code, vscode

## Problem

I am contemplating moving from JSDoc to TypeDoc, but could not find if you support a `@deprecated` tag. It would be a nice additon. E.g. VS Code can infer a lot form this tag and cross-over text for deprecated methods etc.

## Suggested Solution

Support the `@deprecated` tag.

**Comment by Gerrit0** [comment] 2021-03-10 13:37
TypeDoc will render *any* tag you use - so unless there's extra behavior needed to make a tag useful, we technically support it.

I think it would make sense to add some special logic for this one so that it stands out more.

**Comment by cAttte** [comment] 2021-04-11 14:19
isn't this a duplicate of #1381?

**Comment by Gerrit0** [comment] 2021-04-11 16:32
So it is, thanks!

**Closed by Gerrit0** 2021-04-11 16:32 UTC
Labels: enhancement
