### ISSUE TITLE
TypeDoc unable to compile code that TypeScript can

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1234] opened 2020-03-17 18:44 UTC
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

TypeDoc is able to compile code that TypeScript can compile.
## Actual Behavior

The following code compiles perfectly with no errors when I use TypeScript (v3.8.3),
```js
import {Constants, Message} from "eris";

export {Message};
export type PermissionName = keyof Constants["Permissions"];
```
however TypeDoc throws errors that appear to make no sense when trying to compile it:
```
Error: C:/../patron/types/eris.d.ts(0)
 Circular definition of import alias 'Constants'.
Error: C:/../patron/types/eris.d.ts(0)
 Module '"../../../../../../../patron/types/eris"' declares 'Constants' locally, but it is exported as 'Message'.
Error: C:/../patron/types/eris.d.ts(2)
 Circular definition of import alias 'Message'.
```
I have also tried simply using
```js
import "eris";
```
to eliminate the library as a cause, and both TypeScript and TypeDoc can compile this.

## Steps to reproduce the bug

I am running TypeDoc through code, here's my bootstrap method:
```js
app.bootstrap({
  mode: "file",
  target: "ES6",
  includeDeclarations: true,
  excludeNotExported: true
});
```

## Environment
  - Typedoc version: @next or 0.17.0 (both have this)
  - Node.js version: 13.11.0
  - OS: Windows 10

**Comment by Gerrit0** [comment] 2020-03-18 02:19
This is really weird, but this apparently is caused by setting the target to ES6 in TypeDoc's config... I have no idea why.

I installed what appears to be the necessary packages:

```json
{
  "name": "gh1234",
  "license": "MIT",
  "dependencies": {
    "@types/node": "^13.9.1",
    "eris": "^0.11.2",
    "typedoc": "^0.17.0",
    "typescript": "^3.8.3"
  }
}
```

Created a minimal tsconfig.json:

```json
{
  "include": [ "index.ts" ]
}
```

Then pasted the provided code into `index.ts`. I ran TypeDoc through the CLI (fairly minimal wrapper around the provided API, if you enable the TSConfigReader for options there shouldn't be any difference in the configuration).

```bash
yarn typedoc --includeDeclarations --excludeExternals --target ES6 --mode file
```

This failed to find the eris module:

```bash
$ C:\Users\Gerrit\Desktop\gh1234\node_modules\.bin\typedoc --includeDeclarations --excludeExternals --target ES6 --mode file

Using TypeScript 3.8.3 from C:\Users\Gerrit\Desktop\gh1234\node_modules\typescript\lib
Error: C:/Users/Gerrit/Desktop/gh1234/index.ts(0)
 Cannot find module 'eris'.
error Command failed with exit code 4.
```

Dropping `--target ES6` produced output (but didn't include the Eris types because they are considered external as they weren't provided as an input file. Running again with some modifications produced output... but took a while.

```bash
> yarn typedoc --mode file --includeDeclarations --exclude "node_modules/@types/**"
yarn run v1.22.0
$ C:\Users\Gerrit\Desktop\gh1234\node_modules\.bin\typedoc --mode file --includeDeclarations --exclude node_modules/@types/**

Using TypeScript 3.8.3 from C:\Users\Gerrit\Desktop\gh1234\node_modules\typescript\lib
No 'out' or 'json' option has been set
The './docs' directory has be set as the output location by default
Rendering [========================================] 100%

Documentation generated at C:\Users\Gerrit\Desktop\gh1234\docs

Done in 565.41s.
```

![image](https://user-images.githubusercontent.com/19329837/76918276-8fc4be80-688b-11ea-8e19-30de3676a161.png)

Including the readme of a dependency is being tracked in #1066.

This still included too many files, so I instead provided Eris as an input file to prune down what was converted. This worked as expected.

```bash
> yarn typedoc --mode file --includeDeclarations --excludeExternals --out docs2 .\index.ts .\node_modules\eris\
yarn run v1.22.0
$ C:\Users\Gerrit\Desktop\gh1234\node_modules\.bin\typedoc --mode file --includeDeclarations --excludeExternals --out docs2 .\index.ts .\node_modules\eris\

Using TypeScript 3.8.3 from C:\Users\Gerrit\Desktop\gh1234\node_modules\typescript\lib
Rendering [========================================] 100%

Documentation generated at C:\Users\Gerrit\Desktop\gh1234\docs2

Done in 9.56s.
```

![image](https://user-images.githubusercontent.com/19329837/76918604-517bcf00-688c-11ea-8e24-6cd2e2778102.png)
 
Note that the re-export of `Message` was not rendered. This is because in `file` mode, TypeDoc pretends everything is global... so imports/exports don't make any sense. Once finished, library mode will probably be the right mode to use.

**Comment by LJNeon** [comment] 2020-03-18 05:25
This library uses ES6 features, if I try using ES5 instead I get new errors like
```
Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
```
Changing the mode doesn't appear to affect this error whatsoever, so I switched to library on next since you recommended it.

**Comment by Gerrit0** [comment] 2020-03-21 23:14
Any chance you could point me to a repo that I could look at? This seems to work with my setup from before.

```js
const td = require('typedoc')

const app = new td.Application()
app.options.addReader(new td.TSConfigReader());

app.bootstrap({
    mode: "file",
    includeDeclarations: true,
    excludeNotExported: true,
    excludeExternals: true
});

const project = app.convert(app.expandInputFiles(['src', 'node_modules/eris/']));

if (project) { // Project may not have converted correctly
    const outputDir = 'docs';

    // Rendered docs
    app.generateDocs(project, outputDir);
    // Alternatively generate JSON output
    app.generateJson(project, outputDir + '/documentation.json');
}
```

**Comment by LJNeon** [comment] 2020-03-22 12:16
It seems that I misunderstood some of what you said, with that exact code this does appear to work albeit in a strange way (the outermost package in the JSON is actually the dependency, and my package is marked as a child).

**Comment by Gerrit0** [comment] 2020-03-22 17:30
I'm not seeing that. I see Eris and PermissionName at the same level, which is what file mode is supposed to do

File mode is generally a bad idea to use in projects which use modules. It pretends there are no modules and that all symbols are global.

**Comment by LJNeon** [comment] 2020-03-27 00:35
```json
{
	"id": 0,
	"name": "eris",
	"kind": 0,
	"flags": {},
	"originalName": "",
	"children": [
		{
			"id": 5528,
			"name": "\"patron\"",
			"kind": 2,
			"kindString": "Namespace",
			"flags": {
				"isExported": true
			},
			"children": [
```
When I generate JSON with the above code this is what I'm getting, unless I'm reading this wrong it seems to have my library as a child of it's dependency. Also on an unrelated note, when I try switching to library mode I get documentation for the dependency and not for my library.

**Comment by LJNeon** [comment] 2020-03-27 00:38
Also, is there a place to get support other than the Github? I tend to have a lot of questions and mass-opening Github issues doesn't seem like a good idea.

**Comment by Gerrit0** [comment] 2020-03-30 01:36
The `"name": "eris"` probably comes from TypeDoc trying to guess the name from your package.json. The method for detection for the package.json file isn't great (again, #1066) and it is picking up eris's package.json instead of yours.

Feel free to ask questions in the TS Discord or on Gitter, though my response time likely won't really be different than on here, and GitHub has the benefit of documenting questions for others coming looking for them later.

**Comment by Gerrit0** [comment] 2020-06-19 16:56
This seems to have been resolved, closing for cleanup.

**Closed by Gerrit0** 2020-06-19 16:56 UTC
Labels: bug
