### ISSUE TITLE
@inheritdoc is not working

### ISSUE THREAD

**Issue by rochdev** [TypeStrong/typedoc#925] opened 2018-12-21 19:03 UTC
I've seen multiple mentions that this feature is supposedly supported, but it doesn't seem to be working.

For example:

```typescript
declare class Tracer extends opentracing.Tracer {
  /** @inheritdoc */
  inject(spanContext: SpanContext | Span, format: string, carrier: any): void;
}
```

![image](https://user-images.githubusercontent.com/1596303/50358937-f6441b00-0528-11e9-9d16-9809bb573d7b.png)

If I don't override the method the documentation is properly displayed.

**Comment by aciccarello** [comment] 2018-12-21 21:18
Hello @rochdev. There are a few known issues with `@inheritdoc` at the moment. Does the method you are overriding differ at all in its type signature? If so, this might be the same as #793. If no, could you please provide more information about how we can reproduce this?

**Comment by rochdev** [comment] 2018-12-22 15:32
@aciccarello Just tried with the exact same types (no subclass) and it's still not working.

**Comment by rochdev** [comment] 2018-12-22 16:40
FWIW it doesn't seem to work for the class documentation either. I don't know if it's the same issue, or if it's simply not implemented for the class description.

**Comment by benrr101** [comment] 2020-11-22 19:13
I hate to necrobump this issue, but this is one I've been running into on my project (https://github.com/benrr101/node-taglib-sharp). I have classes (eg. [Id3v1Tag](https://github.com/benrr101/node-taglib-sharp/blob/develop/src/id3v1/id3v1Tag.ts)) that inherits from an abstract class ([Tag](https://github.com/benrr101/node-taglib-sharp/blob/develop/src/tag.ts)) that has a lot of long comments for properties I'd like to copy over using `inheritDoc`. While fiddling with syntax to see if I was just doing it wrong, I noticed my classes that inherited from an interface copied over correctly (eg, [ApeStreamHeader](https://github.com/benrr101/node-taglib-sharp/blob/develop/src/ape/apeStreamHeader.ts) inheriting from [ICodec](https://github.com/benrr101/node-taglib-sharp/blob/develop/src/iCodec.ts)). Is it possible the `inheritDoc` functionality just isn't working with abstract class inheritance?

This could totally be a different issue, if so, let me know and I'll make a new issue from this.

**Comment by Gerrit0** [comment] 2020-11-25 20:56
That might be the case... however I also might have fixed this in recent work done on v0.20.

With these changes:

```diff
diff --git a/src/id3v1/id3v1Tag.ts b/src/id3v1/id3v1Tag.ts
index 7fd0154..f053c78 100644
--- a/src/id3v1/id3v1Tag.ts
+++ b/src/id3v1/id3v1Tag.ts
@@ -122,13 +122,8 @@ export default class Id3v1Tag extends Tag {
      */
     public set performers(value: string[]) { this._artist = value ? value.join(";") : ""; }

-    /** @inheritDoc */
+    /** @inheritdoc */
     public get album(): string { return this._album || undefined; }
-    /**
-     * @inheritDoc
-     * @description When stored on disk, only the first 30 bytes of the latin-1 encoded value will
-     *     be stored. This may result in data loss.
-     */
     public set album(value: string) { this._album = value ? value.trim() : ""; }

     /** @inheritDoc */
```

```diff
diff --git a/tsconfig.json b/tsconfig.json
index ac5cf56..bc08008 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -17,11 +17,11 @@
     "./src/**/*"
   ],
   "typedocOptions": {
-    "inputFiles": ["./src"],
+    "entryPoints": ["./src/index.ts"],
     "mode": "modules",
     "out": "docs/",
     "excludePrivate": true,
     "disableSources": true,
     "listInvalidSymbolLinks": true
   }
-}
\ No newline at end of file
+}
```

```diff
diff --git a/package.json b/package.json
index 502b7b9..e48d86a 100644
--- a/package.json
+++ b/package.json
@@ -46,7 +46,7 @@
     "tslint": "^5.13.1",
     "typemoq": "^2.1.0",
     "typescript": "^3.9.7",
-    "typedoc": "^0.19.2",
+    "typedoc": "0.20.0-beta.10",
     "typedoc-plugin-markdown": "^3.0.11",
     "uuid": "^7.0.2"
   }
```

I ran `npx typedoc --plugin none` (typedoc-plugin-markdown doesn't work with 0.20 yet) and it generated this page:

![image](https://user-images.githubusercontent.com/19329837/100280807-012e3400-2f26-11eb-9b19-b2bb3f4168bd.png)

**Comment by benrr101** [comment] 2020-11-30 16:13
Well hot damn, that's great to see! I guess I'll just hang on a bit longer until typedoc-plugin-markdown supports 0.20 (or I get annoyed with markdown and just start hosting the docs as html somewhere else).

Out of curiosity, what was the reason for removing the tsdoc for the `set` accessor?

**Comment by Gerrit0** [comment] 2020-11-30 19:50
There was a bug in the accessor converter that broke things if the set accessor had comments - now fixed, but I didn't realize it when first looking at this issue.

**Closed** 2020-12-28 19:25 UTC
Labels: bug, needs reproduction
