### ISSUE TITLE
Typedoc merging the documentation of types with same names from different types

### ISSUE THREAD

**Issue by KarishmaGhiya** [TypeStrong/typedoc#1201] opened 2020-02-12 00:52 UTC
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

Typedoc should not merge the signature and examples of code from two different files even though they share same type names.

## Actual Behavior

For this package - [@azure/ai-text-analytics](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics), the typedoc is generating the documentation by merging constructor signature from 
[this source file](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts) and the examples from this [auto-generated source file](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/src/generated/textAnalyticsClient.ts) You can see the documenation  [generated here] (https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-ai-text-analytics/1.0.0-preview.2/classes/textanalyticsclient.html ) - see the `Constructors` section

## Steps to reproduce the bug

Run typedoc on the package - [@azure/ai-text-analytics](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics) OR you can follow these steps -
- git clone https://github.com/Azure/azure-sdk-for-js.git
- npm install eng/tools/generate-doc
- node eng/tools/generate-doc/index.js --dgOp "dg" -i "inc" --inc "textanalytics" 
- view the generated documentation on your local machine under `azure-sdk-for-js/docGen` folder

Note: The script uses the following parameters with typedoc command [found here](https://github.com/Azure/azure-sdk-for-js/blob/master/eng/tools/generate-doc/index.js#L198)
```
 '--theme "../../../eng/tools/generate-doc/theme/default"',
                      "--excludePrivate",
                      "--excludeNotExported",
                      '--exclude "node_modules/**/*"',
                      "--ignoreCompilerErrors",
                      "--mode file"
```

## Environment
  - Typedoc version: 0.15.0 to 0.16.9
  - Node.js version: 6.13.x
  - OS: linux/windows

cc : @willmtemple

**Comment by alexandercerutti** [comment] 2020-02-14 18:04
I didn't tried but was expecting this behavior. I'm proposing to add this, if already not available: https://github.com/TypeStrong/typedoc/issues/1203

**Comment by Gerrit0** [comment] 2020-02-16 04:54
File mode is intended for projects which do not use modules. (tsc compilation with `--module none`). It pretends that every file is global, so any declarations with the same name will be merged. This is expected behavior.

Unfortunately, many projects (TypeDoc included) use file mode because modules mode results in incredibly ugly output that reveals internal file paths. This is being remedied with library mode (#1184) but that isn't ready for a stable release yet (though you can try it out by installing `typedoc@next`)

**Comment by KarishmaGhiya** [comment] 2020-02-19 00:46
Thanks @Gerrit0 I will discuss with my team about what route we would want to take to fix our existing docs.

**Closed** 2020-03-15 22:27 UTC
Labels: no bug
