### ISSUE TITLE
Cannot visit multiple pages in GitHub Pages

### ISSUE THREAD

**Issue by luzzif** [TypeStrong/typedoc#620] opened 2017-10-12 06:10 UTC
I have a little TypeScript [ project ]( https://github.com/luzzif/bittrex-api-client ) for which I've written and generated the documentation using TypeDoc, but the only page displaying without problems is the index. What can be done in order to fix this?

**Comment by phillip-elm** [comment] 2017-10-23 18:15
This was answered by @sebastian-lenz in #149. 

The quick fix is to add a `.nojekyll` file to the root directory of your generated docs. Full documentation can be found [here](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/).

**Comment by aciccarello** [comment] 2017-10-23 19:47
Duplicate of #149 

Thanks for pointing that out @phillip-elm

**Closed by aciccarello** 2017-10-23 19:47 UTC
Labels: duplicate

**Comment by meiblorn** [comment] 2018-10-27 20:36
@phillip-elm solution still works

**Comment by igimanaloto** [comment] 2018-11-11 01:53
Also adding a config.yml works:

```
include:
  - "_*_.html"
  - "_*_.*.html"
```

I found that with my latest trial, .nojekyll doesn't display modules/* pages. However, using the config.yml approach works perfectly.

**Comment by jhbertra** [comment] 2019-08-11 01:14
Also found this problem... For what it's worth, I think it is ridiculous and non-obvious that the default behaviour is not to serve static files like a normal HTTP server, regardless if this behaviour is documented.  This should NOT require additional steps to accomplish.

**Comment by Gerrit0** [comment] 2020-01-21 20:04
@yukipastelcat going to the link and clicking on the class name works for me. I'd recommend clearing your cache.

**Comment by ajb413** [comment] 2020-08-25 22:53
Is there a way to automatically add the `.nojekyll` file to the documentation build output folder using the `typedoc` command? It gets deleted every time I rebuild the docs and I have to manually re-add it.
