### ISSUE TITLE
Interface optional parameters does not render type definition

### ISSUE THREAD

**Issue by miqmago** [TypeStrong/typedoc#1375] opened 2020-10-11 23:42 UTC
## Search terms

Interface optional parameters does not render type definition

This interface:

```ts
export interface MyInterface {
    /** Observable to the recording event, defaults to `{}` */
    recording: {
        /**
         * Emit is called each time recording starts or stops
         * @param isRecording Indicates whether it is recording or not
         */
        emit: (isRecording: boolean) => void;
    };
}
```

Renders to:
```html
			
<section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface">
    <a name="recording" class="tsd-anchor"></a>
    <h3>recording</h3>
    <div class="tsd-signature tsd-kind-icon">recording<span class="tsd-signature-symbol">:</span> <span class="tsd-signature-symbol">{ </span>emit<span class="tsd-signature-symbol">: </span><span class="tsd-signature-symbol">(</span>isRecording<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">boolean</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol"> =&gt; </span><span class="tsd-signature-type">void</span><span class="tsd-signature-symbol"> }</span></div>
    <aside class="tsd-sources">
        <ul>
            <li>Defined in interfaces.ts:42</li>
        </ul>
    </aside>
    <div class="tsd-comment tsd-typography">
        <div class="lead">
            <p>Observable function to the recording event, defaults to <code>{}</code></p>
        </div>
    </div>
    <div class="tsd-type-declaration">
        <h4>Type declaration</h4>
        <ul class="tsd-parameters">
            <li class="tsd-parameter">
                <h5>emit<span class="tsd-signature-symbol">: </span><span class="tsd-signature-symbol">(</span>isRecording<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">boolean</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol"> =&gt; </span><span class="tsd-signature-type">void</span></h5>
                <div class="tsd-comment tsd-typography">
                    <div class="lead">
                        <p>Emit is called each time recording starts or stops</p>
                    </div>
                    <dl class="tsd-comment-tags">
                        <dt>param</dt>
                        <dd><p>Indicates whether it is recording or not</p>
                        </dd>
                    </dl>
                </div>
                <ul class="tsd-parameters">
                    <li class="tsd-parameter-signature">
                        <ul class="tsd-signatures tsd-kind-type-literal tsd-parent-kind-variable">
                            <li class="tsd-signature tsd-kind-icon"><span class="tsd-signature-symbol">(</span>isRecording<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">boolean</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">void</span></li>
                        </ul>
                        <ul class="tsd-descriptions">
                            <li class="tsd-description">
                                <h4 class="tsd-parameters-title">Parameters</h4>
                                <ul class="tsd-parameters">
                                    <li>
                                        <h5>isRecording: <span class="tsd-signature-type">boolean</span></h5>
                                    </li>
                                </ul>
                                <h4 class="tsd-returns-title">Returns <span class="tsd-signature-type">void</span></h4>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</section>
````

But when the parameters are optional:

```ts
export interface MyInterface {
    /** Observable to the recording event, defaults to `{}` */
    recording?: {
        /**
         * Emit is called each time recording starts or stops
         * @param isRecording Indicates whether it is recording or not
         */
        emit?: (isRecording: boolean) => void;
    };
}
```

It renders to:

```html
<section class="tsd-panel tsd-member tsd-kind-property tsd-parent-kind-interface">
    <a name="recording" class="tsd-anchor"></a>
    <h3><span class="tsd-flag ts-flagOptional">Optional</span> recording</h3>
    <div class="tsd-signature tsd-kind-icon">recording<span class="tsd-signature-symbol">:</span> <span class="tsd-signature-type">undefined</span><span class="tsd-signature-symbol"> | </span><span class="tsd-signature-symbol">{ </span>emit<span class="tsd-signature-symbol">?: </span><span class="tsd-signature-type">undefined</span><span class="tsd-signature-symbol"> | </span><span class="tsd-signature-symbol">(</span><span class="tsd-signature-symbol">(</span>isRecording<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">boolean</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol"> =&gt; </span><span class="tsd-signature-type">void</span><span class="tsd-signature-symbol">)</span><span class="tsd-signature-symbol"> }</span></div>
    <aside class="tsd-sources">
        <ul>
            <li>Defined in interfaces.ts:42</li>
        </ul>
    </aside>
    <div class="tsd-comment tsd-typography">
        <div class="lead">
            <p>Observable function to the recording event, defaults to <code>{}</code></p>
        </div>
    </div>
</section>
```

## Expected Behavior

It should render both cases with type definition.

## Actual Behavior

Type definition is not rendered when parameters are optional.

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.3
-   Node.js version: v12.19.0
-   OS: macOS Catalina 10.15.6 (19G2021)

**Comment by Gerrit0** [comment] 2020-10-17 17:17
Duplicate of #1202.

**Closed by Gerrit0** 2020-10-17 17:17 UTC
Labels: bug
