### ISSUE TITLE
Type doc mistake Enumeration type as union

### ISSUE THREAD

**Issue by wuhanyumsft** [TypeStrong/typedoc#599] opened 2017-09-26 03:40 UTC
I found an issue that TypeDoc mistake Enumeration type as union type.

Here is a sample:
A property named `artifactType` is a enumeration type named `AgentArtifactType`. But TypeDoc mistake it as a union type, while display its values as the member of union type.

```
{
	"id": 127169,
	"name": "artifactType",
	"kind": 1024,
	"kindString": "Property",
	"flags": {
		"isExported": true
	},
	"sources": [
		{
			"fileName": "rmo.d.ts",
			"line": 148,
			"character": 16
		}
	],
	"type": {
		"type": "union",
		"types": [
			{
				"type": "unknown",
				"name": "AgentArtifactType.XamlBuild"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.Build"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.Jenkins"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.FileShare"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.Nuget"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.TfsOnPrem"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.GitHub"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.TFGit"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.ExternalTfsBuild"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.Custom"
			},
			{
				"type": "unknown",
				"name": "AgentArtifactType.Tfvc"
			}
		]
	}
}
```
Can we fix that?  Thanks.

**Comment by wuhanyumsft** [comment] 2017-10-25 09:43
Is there anyone can help?

**Comment by aciccarello** [comment] 2017-10-25 14:46
I would have expected this to be fixed with #599 though someone else seems to be having an issue with string enums. Are you using the latest version of TypeDoc?

**Comment by fabioberger** [comment] 2017-11-27 17:14
Plus one for this issue. Just ran into it myself with string enums.

**Comment by wuhanyumsft** [comment] 2017-12-01 05:48
I ran the result with typedoc version 0.9.0

**Comment by Gerrit0** [comment] 2019-11-13 04:10
This appears to be fixed, I can't reproduce with 0.15.

https://typedoc.org/api/classes/logger.html#log

**Closed by Gerrit0** 2019-11-13 04:10 UTC
Labels: bug, help wanted
