### ISSUE TITLE
Intersection Types in JSDoc are expanded everywhere

### ISSUE THREAD

**Issue by hugomrdias** [TypeStrong/typedoc#1394] opened 2020-11-12 20:01 UTC
## Search terms

types, intersection

## Expected Behavior

Typedoc should use a link pointing to the intersection type definition when defined with JSDoc.

## Actual Behavior

Typedoc renders all the properties of the intersection type inline everywhere when defined with JSDoc like below
```js
/**
 * @typedef { Type1 & Type2 } InterType
 */

```

When defined in a ts file like below everything works properly 
```ts
export type InterType = Type1 & Type2
```

## Environment

-   Typedoc version: 0.19.2
-   TypeScript version: 4.0.5
-   Node.js version: 14
-   OS: Mac OS

**Comment by Gerrit0** [comment] 2020-11-14 16:10
I believe this will be a duplicate of #1214, TypeDoc doesn't currently have a converter for `@typedef` definitions, so it does its best to get the type using just the type checker.

**Comment by hugomrdias** [comment] 2020-11-16 10:42
after reading your comment, this might not be a typedoc problem, because im feeding typedoc the type declarations instead of the sources (sources are in commonjs).
i will do some more digging

**Comment by Gerrit0** [comment] 2020-12-29 04:38
Closing in favor of #1214

**Closed by Gerrit0** 2020-12-29 04:38 UTC
Labels: bug
