### ISSUE TITLE
Single declaration exports (export =) not handled correctly

### ISSUE THREAD

**Issue by hiranya911** [TypeStrong/typedoc#1456] opened 2021-01-05 23:08 UTC
## Search terms

Single export

## Steps to reproduce the bug

Try generating documentation for a module that exports a [single item](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) using the `export =` syntax.

```typescript
import { FirebaseNamespace } from './firebase-namespace';

const firebaseAdmin = new FirebaseNamespace();

export = firebaseAdmin;
```

The export was documented as a variable in the output.

<img width="830" alt="Screen Shot 2021-01-05 at 3 04 44 PM" src="https://user-images.githubusercontent.com/2375201/103709706-0b514280-4f68-11eb-992a-ae0fcf7332ac.png">

## Environment

-   Typedoc version: 0.20.2
-   TypeScript version: 3.9.6
-   Node.js version: 10.22.0
-   OS: Mac

**Comment by Gerrit0** [comment] 2021-01-06 02:38
This looks like a duplicate of https://github.com/TypeStrong/typedoc/issues/1422

Short answer: handling this is tricky because people can do bad things:

```ts
export const x = 1
```

**Comment by Gerrit0** [comment] 2021-01-09 20:31
Closing in favor of #1422

**Closed by Gerrit0** 2021-01-09 20:31 UTC
Labels: bug
