### ISSUE TITLE
tsconfig option does not take into account tsconfig's location

### ISSUE THREAD

**Issue by kylenicola** [TypeStrong/typedoc#244] opened 2016-06-28 18:08 UTC
I have a directory setup like:

parent/project/out/example.html
parent/project/src/tsconfig.json
parent/project/typings/index.d.ts

The tsconfig file references the typings in the files list.  If I run typedoc in the project directory using the tsconfig option I get an error similar to this:

Error: ENOENT: no such file or directory, stat '**parent**\typings\index.d.ts'

So it's using the the path relative to where typedoc is being run, not relative to where the tsconfig file is located.

**Comment by devpaul** [comment] 2017-04-26 17:46
I ran into this issue recently. I believe the issue is because the option readers don't take into account the source directory provided to the command line/Application.

https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/tsconfig.ts#L34

```typescript
onDiscover(event: DiscoverEvent) {
        if (TSConfigReader.OPTIONS_KEY in event.data) {
            this.load(event, Path.resolve(event.data[TSConfigReader.OPTIONS_KEY]));
        } else if (this.application.isCLI) {
            let file: string = ts.findConfigFile('.', ts.sys.fileExists);
            // If file is undefined, we found no file to load.
            if (file) {
                this.load(event, file);
            }
        }
    }
```

The work-around is to also explicitly define the location using the (non-public) `tsconfig` option.

```typescript
const typescript = require('typescript');
const config = typescript.findConfigFile(source, existsSync);
options.tsconfig = config;
```

FWIW, the typedoc reader suffers the same problem as it assumes configuration files exist relative to the present working directory.

https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/typedoc.ts#L32

These issues could be resolved in the short-term by taking into account the source provided by the `json` or `out` options. However, that isn't a solution for the programmatic usage of Application since `json` and `out` are not required options.

**Closed** 2020-11-28 18:48 UTC
