### ISSUE TITLE
Warning from phantom comments

### ISSUE THREAD

**Issue by crystalfp** [TypeStrong/typedoc#2715] opened 2024-09-27 06:53 UTC
## Search terms

Pinia, link

## Expected Behavior

In the following code (from a Pinia store) I expect no warnings from TSDoc.
```
export const useConfigStore = defineStore("ConfigStore", {

    state: () => ({

		camera: {
	                . . .
		},
		scene: {
			. . .
		},
		lights: {
			. . . 
		},
                helpers: {
                        . . .
                }
	} as Viewer3DConfiguration),

    // > Getters
    getters: {
        /**
         * Return the status to be saved in a project
         *
         * @param state - The store state
         * @returns JSON formatted content of the store to be saved
         */
        statusToSave(state: Viewer3DConfiguration) {
            const statusToSave = {
                camera: state.camera,
                scene: state.scene,
                lights: state.lights,
                helpers: state.helpers,
            };
            return JSON.stringify(statusToSave);
        },
        /**
         * Check if the camera is perspective
         *
         * @param state - The store state
         * @returns True if the camera is set to perspective
         */
        isPerspectiveCamera(state: Viewer3DConfiguration) {
            return state.camera.type === "perspective";
        }
    },
```

## Actual Behavior

Typedoc complains about failed links in non-existent comments for `statusToSave` getter routine. Where it takes the "replace" thing?
```
[warning] Failed to resolve link to "searchValue" in comment for stores/configStore.useConfigStore.statusToSave.replace.replaceValue
[warning] Failed to resolve link to "replaceValue" in comment for stores/configStore.useConfigStore.statusToSave.replace
[warning] Failed to resolve link to "searchValue" in comment for stores/configStore.useConfigStore.statusToSave.replace
```
Strange enough, no complain from the second getter, even it has the same structure.

## Steps to reproduce the bug
1. Put the above code in a file called `configStore.ts`
2. Run the following code:
```
root=`pwd | sed "s@/d/@/d:/@"`
node_modules/.bin/typedoc \
--name "See the Molecule new generation" \
--out "doc/typedoc" \
--readme none \
--suppressCommentWarningsInDeclarationFiles \
--plugin typedoc-plugin-vue \
--plugin @zamiell/typedoc-plugin-not-exported \
--disableGit \
--excludeInternal \
--sourceLinkTemplate "vscode://file$root/{path}:{line}:1" \
--tsconfig ./tsconfig.json \
configStore.ts
```

## Environment

-   Typedoc version: 0.26.7
-   TypeScript version: 5.6.2
-   Node.js version: 22.5.1
-   OS: Windows 11 64bits

**Comment by Gerrit0** [comment] 2024-09-28 16:54
Can this be reproduced without plugins? Bugs caused by plugins should be reported to that plugin, not to this project.

**Comment by electrovir** [comment] 2024-09-28 17:40
My warnings look slightly different:

```
[warning] Failed to resolve link to "searchValue" in comment for __type.replaceValue
[warning] Failed to resolve link to "replaceValue" in comment for __type
[warning] Failed to resolve link to "searchValue" in comment for __type
```

Nowhere in my codebase is anything named `searchValue` or `replaceValue`.

Repro is on this branch: https://github.com/electrovir/date-vir/tree/broken-docs. Repro steps are as follows:

1. `npm i` in root
2. `cd packages/date-vir && npm run docs`

I'm also getting a project warning which I don't understand because I've never gotten it before and I use the same config in all my repos.

```
[warning] date-vir (Project), defined in ./src/index.ts, does not have any documentation
```

I've narrowed the issue down to this line: https://github.com/electrovir/date-vir/blob/broken-docs/packages/date-vir/src/timezone/timezones.ts#L10

When I remove line 10, TypeDoc doesn't error out. It appears that TypeDoc is unable to handle this situation where an object is made to behave like a TypeScript `enum`.

I haven't found a workaround yet; adding `@ignore` doesn't work.

**Comment by electrovir** [comment] 2024-09-28 17:50
Solution for my problem: remove `@enum` from the `Timezone` const. TypeDoc was incorrectly expanding the enum properties anyway, grabbing all the string properties from the `Timezone` _type_ (which is a string union). It's unfortunate that I can't have that object marked as an enum in TypeDoc's output.

**Comment by crystalfp** [comment] 2024-09-29 09:46
@Gerrit0 The problem does not happen without plugins, but happens with any plugin.
OK, I will open the issue with both of the plugins I use, but the doubt remains: could be the mere presence of plugin to trigger the phantom comments?

**Comment by Gerrit0** [comment] 2024-09-29 15:03
No, this is almost certainly caused by a plugin doing something weird. One of the plugins is likely converting something defined in node_modules as a part of your code.

Closing as this issue doesn't appear to be caused by typedoc

**Closed by Gerrit0** 2024-09-29 15:03 UTC
Labels: bug
