### ISSUE TITLE
Typedoc not starting. Constant errors output with `basePath` and `comments`.

### ISSUE THREAD

**Issue by conmute** [TypeStrong/typedoc#346] opened 2016-11-25 16:15 UTC
Terminal output:

```
> typedoc

> qad-js-webui@1.0.0 doc /home/rko/Documents/project/js-webui
> typedoc

Error: Unknown option `basePath`.
Error: Unknown option `comments`.

npm ERR! Linux 4.8.0-040800-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "doc"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! qad-js-webui@1.0.0 doc: `typedoc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qad-js-webui@1.0.0 doc script 'typedoc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the qad-js-webui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typedoc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs qad-js-webui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls qad-js-webui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rko/Documents/project/js-webui/npm-debug.log
```

```
> grunt typedoc

> qad-js-webui@1.0.0 doc /home/rko/Documents/project/js-webui
> grunt typedoc

Running "typedoc:build" (typedoc) task
Error: Unknown option `basePath`.
Error: Unknown option `comments`.
Warning: Task "typedoc:build" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.8.0-040800-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "doc"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! qad-js-webui@1.0.0 doc: `grunt typedoc`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the qad-js-webui@1.0.0 doc script 'grunt typedoc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the qad-js-webui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt typedoc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs qad-js-webui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls qad-js-webui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rko/Documents/project/js-webui/npm-debug.log
```

**Comment by conmute** [comment] 2016-11-25 16:26
```
$ typedoc --version
Error: Unknown option `basePath`.
Error: Unknown option `comments`.
```

:D

**Comment by aciccarello** [comment] 2016-11-25 16:47
Hello @conmute. I believe this is a duplicate of #340 though I'm not sure what the comments option refers to.

**Comment by aciccarello** [comment] 2017-02-02 17:05
@conmute Do you still have this issue with the latest version of TypeDoc? If so can you share your `tsconfig.json` setup?

**Closed** 2020-02-28 04:29 UTC
