### ISSUE TITLE
Creating doc from Mocha test

### ISSUE THREAD

**Issue by c0ncentus** [TypeStrong/typedoc#1073] opened 2019-07-17 09:57 UTC
## Problem
Typedoc doent provide doc from test ... Tests (unit test and other) is a doc, 
why dont implement it, in different section ?

## Suggested Solution
make plug in ? #

**Comment by Gerrit0** [comment] 2019-07-18 02:20
I'm confused as to what benefit this would provide.

TypeDoc creates api documentation to provide an overview of the API in a project... I'm not sure what documenting tests would even look like. They can provide useful examples, but in my experience targeted examples are far more useful than just saying "here's a test for every feature, go search to find the one that is relevant to your issue"

.. that said, I'm probably missing your use case. What were you looking for?

**Comment by c0ncentus** [comment] 2019-07-18 05:55
```  Describe  debug Versus debug
    √ It Should  return false

  Describe  error Versus debug
    √ It Should  return true
```

Any test you made, it should be clear what you test , what you expected in particular function .... 
is technical documentation .... 

https://capgemini.github.io/development/unit-tests-as-documentation/

**Comment by aciccarello** [comment] 2019-07-18 14:49
I'm going to mark this as a duplicate of #821 

I like the idea but for now I will say it is out of scope for typedoc. Typedoc is focused on documenting the symbols of your code and it's HTML output can be used alongside other forms of documentation such as reference documentation or a tool that could document tests.

**Closed by aciccarello** 2019-07-18 14:49 UTC
