### ISSUE TITLE
Wrong id in inheritedFrom section

### ISSUE THREAD

**Issue by SavchenkoAlexander** [TypeStrong/typedoc#1230] opened 2020-03-16 08:30 UTC
When generating from d.ts file the resulting part of json file is
```
"id": 160728,
"name": "ASPxClientGaugeControl",
"kind": 128,
"kindString": "Class",
"flags": {
	"isExported": true
},
"children": [						
	{
		"id": 160760,
		"name": "Init",
		"kind": 1024,
		"kindString": "Property",
		...
		"inheritedFrom": {
			"type": "reference",
			"id": 160760,
			"name": "ASPxClientControlBase.Init"
		}
	},
	...
]
```

- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
The "id" value in inheritedFrom section should be as the id of "Init" property of the ASPxClientControlBase class.

## Actual Behavior
The "id" value in inheritedFrom section is the id of "Init" property of the ASPxClientGaugeControl class (the inherited member itself).

## Steps to reproduce the bug

typedoc --json tsDoc.json --ignoreCompilerErrors --includeDeclarations --excludePrivate --target ES5 d:\Temp

## Environment
  - Typedoc version: 0.16.11
  - Node.js version: 12.13.1
  - OS: Windows 10

**Comment by Gerrit0** [comment] 2020-03-18 03:44
The whole system surrounding TypeDoc's reference types really needs to be redone...

We currently frequently try to guess what a reference is referring to given nothing but its name. While this might have worked decently well in pre-module TypeScript.... it is a horrible idea now.

I spent a few hours looking into this yesterday and partially fixed it, but ran into several other blockers that will need some more hours to figure out. I should be able to look more deeply into it this weekend.

**Comment by donmccurdy** [comment] 2020-05-03 19:46
I'm not familiar with the generated JSON here, but I think I'm seeing the same issue. I have a class hierarchy that looks like this:

<img width="521" alt="Screen Shot 2020-05-03 at 12 42 46 PM" src="https://user-images.githubusercontent.com/1848368/80924006-99bb5780-8d3b-11ea-995d-6dbed088b116.png">

Most of those classes inherit a number of methods from *Property*, but the generated documentation shows it all as inherited from *Node*, which is a final class not extended by anything. For example, here's the documentation for `getName()` on the *Node* class, which claims to be inherited from itself:

<img width="910" alt="Screen Shot 2020-05-03 at 12 44 21 PM" src="https://user-images.githubusercontent.com/1848368/80924053-d25b3100-8d3b-11ea-802d-fc83f994be1c.png">

Is this the same bug, or have I misunderstood the description?

**Comment by johnDance** [comment] 2020-05-12 18:39
We are also running into the same issue. Sometimes the inherited from references its own class, sometimes a sibling class, and sometimes the actual base class.

**Comment by Gerrit0** [comment] 2020-05-17 03:27
That sounds like the same bug, it sounds like we have a check inverted somewhere for which node to add the inherited from property to.

> I spent a few hours looking into this yesterday and partially fixed it, but ran into several other blockers that will need some more hours to figure out. I should be able to look more deeply into it this weekend.

This never happened... GitHub's old notification system didn't save the notification and it dropped off my radar. PR welcome if someone wants to take a look at fixing this. I need to try to get library mode finished first.

**Comment by CoreyDotCom** [comment] 2020-08-06 20:35
@Gerrit0 is this a duplicate of https://github.com/TypeStrong/typedoc/issues/1209?

**Comment by Gerrit0** [comment] 2020-08-09 00:54
It might be, all of TypeDoc's logic regarding reference resolving is sketchy at best. I'll keep both open for now.

**Closed** 2020-12-28 19:25 UTC
Labels: bug
