### ISSUE TITLE
Not exported interfaces with same name will be overwritten based on file name

### ISSUE THREAD

**Issue by wulkanat** [TypeStrong/typedoc#1373] opened 2020-10-07 05:19 UTC
## Search terms

wrong type, wrong interface

## Expected Behavior

When referencing a non-exported interface, it should use the interface from the file.

## Actual Behavior

When referencing a non-exported interface, it might, depending on the file name, use interfaces of the same name from other files that are also not exported.

## Steps to reproduce the bug

[Minimal Repository](https://github.com/wulkanat/TypeDocReferenceTypeIssue)

Packages:
```
"typedoc": "0.19.2",
"typescript": "4.0.3",
"ts-node": "9.0.0"
"@types/node": "14.11.5"
```

## Environment

-   Typedoc version: `0.19.2`
-   TypeScript version: `4.0.3`
-   Node.js version: `14.11.5`
-   OS: `Windows 10`

**Comment by Gerrit0** [comment] 2020-10-17 17:16
Thanks for the reproduction!

This one goes back to the same problem as it always seems to be with references... TypeDoc tries to do its own handling instead of relying on the compiler api. It works properly with exported symbols at least...

This probably won't be fixed... Documenting non-exported members is a non-goal of library mode, which is where all my time is going right now.

**Closed** 2020-12-30 00:33 UTC
Labels: bug, reproduced, wontfix
