### ISSUE TITLE
Module names in indexes always wrapped in quotes

### ISSUE THREAD

**Issue by rondonjon** [TypeStrong/typedoc#1376] opened 2020-10-12 20:44 UTC
## Search terms

Index, Module, Name, Quotes

## Expected Behavior

Module names in indexes should be displayed just like functions, classes, etc., with their respective, type-specific styles.

## Actual Behavior

Module names are always wrapped in quotes.

Expected: [icon] foo/bar

Actual: [icon] "foo/bar"

## Environment

-   Typedoc version: 0.19.2

**Comment by Gerrit0** [comment] 2020-10-17 17:26
Duplicate of #68 - this is being addressed as a part of the library mode work being tracked in #1364.

**Closed** 2020-10-17 17:26 UTC
Labels: bug
