### ISSUE TITLE
excludeNotExported with default export declaration separate from variable creation not working

### ISSUE THREAD

**Issue by nicknisi** [TypeStrong/typedoc#393] opened 2017-01-26 21:19 UTC
In a module where the default export is defined separate from the creation of the exported value, TypeDoc can't seem to map the exported value back to the internal variable.

Example module:

```ts
// keys.ts 

/**
 * A list of special keys
 */
const keys = {
    foo: 'foo',
    bar: true
};

export default keys;
```

This generates a page that looks like this:

<img width="1013" alt="screen shot 2017-01-26 at 3 08 00 pm" src="https://cloud.githubusercontent.com/assets/293805/22350501/a834daac-e3d9-11e6-9c8a-f6cf8d97472c.png">

**Comment by paztis** [comment] 2020-01-16 12:21
What the final status for this?  Problem is still present and not resolved since 2 years?
On my side I still see it

**Comment by Gerrit0** [comment] 2020-01-16 18:19
Yes, it's still broken. *Most* cases with exports separate from declarations were fixed in 0.16, but default exports and `export = ` haven't been resolved yet. We need a clearer way of presenting that a symbol is exported under `default` or with `export =` in the themes. Once that's done, it should be relatively easy to update the converter.

Nobody works on TypeDoc full time, I've been lucky enough to get a lot done the past month or so, but will soon have much less time to dedicate to it.

**Comment by paztis** [comment] 2020-01-16 18:45
To well understand, the problem is present in the rendering part or the introspection part ?

**Comment by Gerrit0** [comment] 2020-01-16 18:50
I believe both need to be updated to properly fix this.

- The themes need to be updated to clearly mark if some reflection is the default export
- The converter needs to be updated to mark a reflection as a default export even if it isn't in that declaration.

**Comment by paztis** [comment] 2020-01-16 18:53
But the typescript reflection detect it. In this case the problem is fully internal.
Why the previous PR was not accepted ? Why try to look for a better solution if I we'll understand the problem.

**Comment by paztis** [comment] 2020-01-16 23:35
as I see in the code, the exports are not checked at the good level.
The SourceFile object itself containt all the correct references to the exports.
You are searching for ExportAssignment and ExportDeclaration that are only present when a variable is declared inside an export
`export const x = 1`

On an existing variable export no node exist
`cosnt x = 1; export default x`

Will try to rewrite it

**Comment by Gerrit0** [comment] 2020-01-17 04:47
> Why the previous PR was not accepted ?

I'm not sure, I wasn't involved much then, based on the comments it looks like it never solved the issue of telling if a reflection was the default export.

> You are searching for ExportAssignment and ExportDeclaration that are only present when a variable is declared inside an export

I think it should be possible to check the source file exports map (exported under "default") and mark a node exported if its symbol is the same symbol.

**Comment by benmccann** [comment] 2020-02-19 19:03
@Gerrit0 highlighting default exports sounds like a reasonable feature, but is really orthogonal to this bug. Do you think you could chime in on https://github.com/TypeStrong/typedoc/pull/431 to encourage the author to continue with his PR?

**Comment by paztis** [comment] 2020-02-19 19:20
I've works on a for of typedoc that correctly supports the lib management

There's a PR over this branch: https://github.com/TypeStrong/typedoc/pull/1196
The typedoc module is also available in @paztis/typedoc over npm (https://www.npmjs.com/package/@paztis/typedoc).

This is globally working with the new 'library' mode of typedoc

You can try if you want

**Comment by Gerrit0** [comment] 2020-02-22 20:37
Yea, I'm with paztis here, I don't really want to pick this up when it should be fixed properly by library mode (which should replace most if not all uses of the other modes)

You can also install `typedoc@next` to try it now, I haven't had time to look at paztis' additional work on it yet.

**Comment by Gerrit0** [comment] 2020-12-29 00:15
This works properly in 0.20:

![image](https://user-images.githubusercontent.com/19329837/103250267-4d5b0280-4930-11eb-9f0b-ebcddf70d0e0.png)

**Closed by Gerrit0** 2020-12-29 00:15 UTC
Labels: bug
