### ISSUE TITLE
Duplicated documetation for method that returns a function

### ISSUE THREAD

**Issue by jonchardy** [TypeStrong/typedoc#2375] opened 2023-08-25 14:42 UTC
## Search terms

Function return

## Expected Behavior

For methods that return functions, documentation should not be duplicated for both the summary comment and the function return signature documentation.

It should probably look something like this:
![image](https://github.com/TypeStrong/typedoc/assets/1202288/118eec6e-f119-4cfc-bd2f-7016d0e727d8)

## Actual Behavior

See duplicated documentation generated:
![image](https://github.com/TypeStrong/typedoc/assets/1202288/9e3d929c-e943-4671-a9e6-e825da940c2f)

## Steps to reproduce the bug

Repro here:
https://github.com/TypeStrong/typedoc-repros/pull/31

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.6
-   Node.js version: 18.13.0
-   OS: Windows 11

**Comment by Gerrit0** [comment] 2023-08-25 19:11
Duplicate of #2336

**Closed by Gerrit0** 2023-08-25 19:11 UTC
Labels: bug
