### ISSUE TITLE
Documenting destructured parameters

### ISSUE THREAD

**Issue by Bibliofile** [TypeStrong/typedoc#653] opened 2017-12-03 04:00 UTC
I'm not entirely sure if this is a bug, enhancement, or just a misunderstanding on my part. How should I document this function?

Given the following source:

```ts
/**
 * @param b a string
 * @param c some number
 */
function dest({ a: b, b: { c } }: { a: string, b: { c: number } }): string {
  let out = '';
  for (let i = 0; i < c; i++) out += b
  return out
}
```

I would expect output similar to the following:

> **dest**
> ```ts
> dest(__namedParameters: object): string
> ```
> **Parameters**
> - **__namedParameters**: *object*
>    - **a**: *string* a string
>    - **b**: *object*
>       - **c**: *number* a number

Instead, this is generated

> **dest**
> ```ts
> dest(__namedParameters: object): string
> ```
> **Parameters**
> - **__namedParameters**: *object*
>   - **b**: *object* a string
>     - **c**: *number*

The documentation for `__namedParameters.a` is dropped since the value is assigned to `b` and the application gets confused with the `b` property (I believe this is a rather obscure bug). A related, less obscure bug, is that if destructuring is used in two parameters, they will both be referred to as `__namedParameters` in the generated documentation.

**Comment by aciccarello** [comment] 2017-12-04 14:38
This may be a duplicate of #522

**Comment by Bibliofile** [comment] 2017-12-04 16:10
I don't believe this is a duplicate, that issue seems to have been fixed as the first example works. 

A simpler reproduction:

```ts
/**
 * @param b a string
 * @param c some number
 */
function dest({ a: b, b: c }: { a: string, b: number }): string {
}
```

I believe it would be better to document parameters based on the type definition rather than the assigned argument, that is, I believe it would be better to document this function like this:

```ts
/**
 * @param a a string
 * @param b some number
 */
function dest({ a: b, b: c }: { a: string, b: number }): string {
}
```

Or, reducing the potential for ambiguity (and following VSCode's autocomplete)


```ts
/**
 * @param param0.a a string
 * @param param0.b some number
 */
function dest({ a: b, b: c }: { a: string, b: number }): string {
}
```

**Comment by kctang** [comment] 2017-12-14 05:17
I encountered similar issue. I suspect this is not a supported feature (not sure if there are any plans to support it).

So, as a workaround, I am going to avoid destructuring when declaring the function. Instead, just specify the object's name (i.e. `input`). On the first line of the function, do the same destructuring.

One extra line, much better looking docs - worth it. :-)

<img width="852" alt="typedoc-destruc-param" src="https://user-images.githubusercontent.com/1495212/33976551-9f3b1390-e0d0-11e7-9cd8-7e0e22174480.png">

**Comment by sassanh** [comment] 2019-05-06 17:11
@kctang I can't make it work as in your screen shots. Can you provide the doc comment on top of your function that works with your method?

**Comment by Zemnmez** [comment] 2019-06-21 14:23
I've discovered you can use normal object destructuring *and* get param comments if you do it like so:
```javascript
export const useOAuth2Token = ({
  /**
   * efc
   */
  authorizeUrl,
  scope = [],
  redirectUri,
  clientID
}: {
  authorizeUrl: string
  scope: string[],
  redirectUri: string,
  clientID: string
}) => {
```

Which results in this:

![image](https://user-images.githubusercontent.com/4625198/59929328-814e9100-9438-11e9-844c-8bb79f147f39.png)

**Comment by Gerrit0** [comment] 2020-11-28 18:19
In TypeDoc 0.20, the original code renders as:

![image](https://user-images.githubusercontent.com/19329837/100523160-80607980-316b-11eb-8fd8-d65b0d457d8f.png)

Which seems mostly reasonable to me (though I was somewhat surprised that "some number" was attached to `c`)

**Closed** 2020-12-28 19:21 UTC
Labels: bug
