### ISSUE TITLE
Allow to pass github user/project from options

### ISSUE THREAD

**Issue by egoist** [TypeStrong/typedoc#753] opened 2018-04-17 16:18 UTC
Currently it's using the output of:

https://github.com/TypeStrong/typedoc/blob/eff16996c653c3fbe960f9c25a76b0210f50801e/src/lib/converter/plugins/GitHubPlugin.ts#L51

However it might be not defined in a continuous deployment environment like netlify.com so the *link to source file* isn't working.

A flag like `--gitRemote https://github.com/user/project` would help.

**Comment by egoist** [comment] 2019-01-29 15:47
Here's a workaround if you're using Netlify, run following command first in your build command:

```bash
git remote add origin git@github.com:$user/$repo.git
```

**Comment by aciccarello** [comment] 2019-01-31 05:20
Sounds like a good suggestion. PRs are welcome. Should be able to add an option in that GitHubPlugin file.

**Comment by artentica** [comment] 2019-02-08 10:40
Seems to already been implemented => https://github.com/TypeStrong/typedoc/pull/843
@aciccarello

**Comment by aciccarello** [comment] 2019-02-08 16:18
@artentica That adds support for different github host names. I don't believe it supports different user logins though.

**Comment by artentica** [comment] 2019-02-08 16:51
In seing the title i undestand it correspond to this: https://github.com/TypeStrong/typedoc/blob/eff16996c653c3fbe960f9c25a76b0210f50801e/src/lib/converter/plugins/GitHubPlugin.ts#L34
Wich is only few month old

**Comment by aciccarello** [comment] 2019-02-08 17:21
True, I misunderstood this issue. I think the remaining issue is that that is pulled from `git ls-remote --get-url`. However, looking at the workaround @egoist posted, I do think that we should be able to close this.

**Closed by aciccarello** 2019-02-08 17:21 UTC
Labels: enhancement, good first issue, help wanted

**Comment by domoritz** [comment] 2021-11-17 19:22
I don't think setting the remote is always enough. The issue is that different users may have different setups.
