### ISSUE TITLE
Website "typedoc.io" is not reachable

### ISSUE THREAD

**Issue by fgeorges** [TypeStrong/typedoc#306] opened 2016-10-13 12:31 UTC
The website "typdoc.io" is not reachable.  It is mentioned in the top-level README file (i.e. there: https://github.com/TypeStrong/typedoc#preview).  Not sure whether this is a typo here or if the website is down.

**Comment by blakeembrey** [comment] 2016-10-13 14:32
Please search existing issues. Duplicate of https://github.com/TypeStrong/typedoc/issues/270.

**Closed by blakeembrey** 2016-10-13 14:32 UTC
