### ISSUE TITLE
Can't link to a section of another document

### ISSUE THREAD

**Issue by jameslan** [TypeStrong/typedoc#2707] opened 2024-09-14 05:20 UTC
## Search terms

markdown link section

## Expected Behavior
In a markdown document,

```markdown
[Virtual IO](parsing.md#virtualio-and-xinclude)
```
should create a link to another document.

## Actual Behavior
Got a warning:
> [warning] The relative path parsing.md#md:virtualio-and-xinclude is not a file and will not be copied to the output directory

and the link in the html doesn't work

## Steps to reproduce the bug

- Create two markdown files: `parsing.md` and `validate.md`;
- Add section 
```markdown
## VirtualIO and XInclude
```
in `parsing.md`.
- add `[Virtual IO](parsing.md#virtualio-and-xinclude)` in `validate.md`.
- Add both markdown file to project documents.

If there's no section part, i.e. `[Virtual IO](parsing.md)` works.

## Environment

-   Typedoc version: 0.26.7
-   TypeScript version: 5.3.3
-   Node.js version: 18.19.0
-   OS: MacOS Sonoma 14.6.1

**Comment by Gerrit0** [comment] 2024-09-14 11:03
Duplicate of #2687

**Closed** 2024-09-23 01:32 UTC
Labels: bug
