### ISSUE TITLE
Typedoc crashes on M1 MacOS computers with an OOM error

### ISSUE THREAD

**Issue by evantahler** [TypeStrong/typedoc#1491] opened 2021-02-01 01:01 UTC
## Search terms

wasm code commit Allocation failed process out of memory heap stacktace GC M1 OSX MacOS 

## Expected Behavior

`typedoc` does not crash with an OOM error

## Actual Behavior

`typedoc` crashes.  Visit https://github.com/actionhero/node-resque/issues/513 for full stacktrace

## Steps to reproduce the bug

On an M1 Mac, `typedoc` crashes.  On Intel-based macs, `typedoc` works fine.  `typedoc` also works fine on Ubuntu environments.  

This error was seen in the `node-resque` project, and can be reproduced by:
1. Get a new M1 Mac...
2. git clone https://github.com/actionhero/node-resque.git && cd node-resque
3. npm install (which will run `npm run prepare`, which will run `typedoc`)
4. See the crash

## Environment

-   Typedoc version: `0.20.18`
-   TypeScript version: `4.1.3`
-   Node.js version: `v12.20.1`
-   OS: MacOS Big Sur + M1 Ship

## Related Issues
- https://github.com/TypeStrong/typedoc/issues/835
- https://github.com/actionhero/node-resque/issues/513

**Comment by evantahler** [comment] 2021-02-01 01:02
cc @bleonard

**Comment by Gerrit0** [comment] 2021-02-01 01:20
Well... I'm sorry to say there's very little I can do here. I don't have the budget for a new Mac just to debug typedoc. I tried pulling it down on the machine I do have, and it worked properly.

Unfortunately, the stack trace is also incredibly unenlightening - all that is in the node internals, nothing to hint towards what TypeDoc did to aggravate this issue.

Editing `node_modules/typedoc/bin/typedoc` to add `Error.stackTraceLimit = 100` might help some.

**Comment by evantahler** [comment] 2021-02-01 01:52
Yeah... I don't have a way to test it either :/

@bleonard Could you try running the same `typedoc` command in node-resque within rosetta mode, to ensure that that this bug is at least limited to M1 Macs?  (you'll likely need to remove and re-install all node_modules)

**Comment by bleonard** [comment] 2021-02-01 02:33
It works on node 15, which might know more about the M1 and memory.

Some logs (12, 14, 15):
```
➜  node-resque git:(master) ✗ node_modules/.bin/typedoc --out docs --theme default src/index.ts

<--- Last few GCs --->

[51704:0x150008000]     1859 ms: Scavenge 153.5 (174.0) -> 140.7 (175.3) MB, 1.4 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure 
[51704:0x150008000]     1906 ms: Scavenge 155.4 (175.5) -> 143.1 (177.8) MB, 1.5 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure 
[51704:0x150008000]     1940 ms: Scavenge 157.3 (177.8) -> 144.0 (179.3) MB, 1.0 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: wasm code commit Allocation failed - process out of memory
 1: 0x10417b344 node::Abort() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 2: 0x10417b4c4 node::errors::TryCatchScope::~TryCatchScope() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 3: 0x10429ab98 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 4: 0x10429ab2c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 5: 0x1047d32dc v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(v8::internal::wasm::NativeModule*, unsigned long, v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 6: 0x1047d41b8 v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegion(unsigned int, v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 7: 0x1047d3680 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 8: 0x1047d3ff4 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, bool, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 9: 0x1047d6234 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
10: 0x1047dcb3c v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
11: 0x1047dca84 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
12: 0x1047b5464 v8::internal::wasm::AsyncCompileJob::CreateNativeModule(std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
13: 0x1047be178 v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(v8::internal::wasm::AsyncCompileJob*) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
14: 0x1047bea08 v8::internal::wasm::AsyncCompileJob::CompileTask::RunInternal() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
15: 0x1041dafa4 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
16: 0x1041d9fbc node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
17: 0x10492fac8 uv__async_io [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
18: 0x104941688 uv__io_poll [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
19: 0x10492ff58 uv_run [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
20: 0x1041b68b4 node::NodeMainInstance::Run() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
21: 0x104155604 node::Start(int, char**) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
22: 0x18df20f34 start [/usr/lib/system/libdyld.dylib]
[1]    51704 abort      node_modules/.bin/typedoc --out docs --theme default src/index.ts
➜  node-resque git:(master) ✗ nvm use 14
Now using node v14.15.4 (npm v6.14.10)
➜  node-resque git:(master) ✗ node_modules/.bin/typedoc --out docs --theme default src/index.ts

<--- Last few GCs --->

[51995:0x130008000]     1841 ms: Scavenge 160.3 (180.0) -> 147.9 (182.0) MB, 1.4 / 0.0 ms  (average mu = 0.990, current mu = 0.990) allocation failure 
[51995:0x130008000]     1870 ms: Scavenge 161.6 (182.0) -> 148.7 (184.0) MB, 1.0 / 0.0 ms  (average mu = 0.990, current mu = 0.990) allocation failure 
[51995:0x130008000]     1903 ms: Scavenge 163.9 (184.0) -> 149.6 (185.0) MB, 0.6 / 0.0 ms  (average mu = 0.990, current mu = 0.990) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: wasm code commit Allocation failed - process out of memory
 1: 0x1003a69d8 node::Abort() [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 2: 0x1003a6b58 node::errors::TryCatchScope::~TryCatchScope() [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 3: 0x1004c0384 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 4: 0x1004c0318 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 5: 0x100a55cdc v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(v8::internal::wasm::NativeModule*, unsigned long, v8::base::AddressRegion, v8::internal::wasm::WasmCodeAllocator::OptionalLock const&) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 6: 0x100a56970 v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegion(int, v8::base::AddressRegion, v8::internal::wasm::WasmCodeAllocator::OptionalLock const&) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 7: 0x100a55638 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion, v8::internal::wasm::WasmCodeAllocator::OptionalLock const&) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 8: 0x100a56780 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
 9: 0x100a58cf4 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
10: 0x100a64808 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, unsigned long) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
11: 0x100a33b54 v8::internal::wasm::AsyncCompileJob::CreateNativeModule(std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, unsigned long) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
12: 0x100a33d1c v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule(std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, unsigned long) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
13: 0x100a3c380 v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(v8::internal::wasm::AsyncCompileJob*) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
14: 0x100a3c14c v8::internal::wasm::AsyncCompileJob::CompileTask::RunInternal() [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
15: 0x100403c08 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
16: 0x1004028a0 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
17: 0x100bb9c20 uv__async_io [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
18: 0x100bcb7e0 uv__io_poll [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
19: 0x100bba0b0 uv_run [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
20: 0x1003def40 node::NodeMainInstance::Run() [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
21: 0x10037f7d0 node::Start(int, char**) [/Users/brian/.nvm/versions/node/v14.15.4/bin/node]
22: 0x18df20f34 start [/usr/lib/system/libdyld.dylib]
[1]    51995 abort      node_modules/.bin/typedoc --out docs --theme default src/index.ts
➜  node-resque git:(master) ✗ nvm use 15
Now using node v15.7.0 (npm v7.4.3)
➜  node-resque git:(master) ✗ node_modules/.bin/typedoc --out docs --theme default src/index.ts
Rendering [========================================] 100%
Info: Documentation generated at /Users/brian/actionhero/node-resque/docs
```

**Comment by bleonard** [comment] 2021-02-01 02:41
I tried it on v12 and set the stack level as requested.


```
➜  node-resque git:(master) ✗ nvm use 12 
Now using node v12.20.1 (npm v6.14.10)
➜  node-resque git:(master) ✗ subl node_modules/.bin/typedoc                                   
➜  node-resque git:(master) ✗ node_modules/.bin/typedoc --out docs --theme default src/index.ts
Error.stackTraceLimit = Infinity;

<--- Last few GCs --->

[53241:0x150008000]     1889 ms: Scavenge 153.1 (181.1) -> 140.7 (181.1) MB, 1.1 / 0.0 ms  (average mu = 0.996, current mu = 0.996) allocation failure 
[53241:0x150008000]     1922 ms: Scavenge 154.7 (181.1) -> 141.5 (181.1) MB, 1.1 / 0.0 ms  (average mu = 0.996, current mu = 0.996) allocation failure 
[53241:0x150008000]     2034 ms: Scavenge 156.8 (181.1) -> 142.5 (181.1) MB, 1.8 / 0.0 ms  (average mu = 0.996, current mu = 0.996) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: wasm code commit Allocation failed - process out of memory
 1: 0x102af3344 node::Abort() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 2: 0x102af34c4 node::errors::TryCatchScope::~TryCatchScope() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 3: 0x102c12b98 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 4: 0x102c12b2c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 5: 0x10314b2dc v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(v8::internal::wasm::NativeModule*, unsigned long, v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 6: 0x10314c1b8 v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegion(unsigned int, v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 7: 0x10314b680 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 8: 0x10314bff4 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, bool, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
 9: 0x10314e234 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
10: 0x103154b3c v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
11: 0x103154a84 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
12: 0x10312d464 v8::internal::wasm::AsyncCompileJob::CreateNativeModule(std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
13: 0x103136178 v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(v8::internal::wasm::AsyncCompileJob*) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
14: 0x103136a08 v8::internal::wasm::AsyncCompileJob::CompileTask::RunInternal() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
15: 0x102b52fa4 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
16: 0x102b51fbc node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
17: 0x1032a7ac8 uv__async_io [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
18: 0x1032b9688 uv__io_poll [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
19: 0x1032a7f58 uv_run [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
20: 0x102b2e8b4 node::NodeMainInstance::Run() [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
21: 0x102acd604 node::Start(int, char**) [/Users/brian/.nvm/versions/node/v12.20.1/bin/node]
22: 0x18df20f34 start [/usr/lib/system/libdyld.dylib]
[1]    53241 abort      node_modules/.bin/typedoc --out docs --theme default src/index.ts
```

**Comment by bleonard** [comment] 2021-02-01 02:46
I tried running some commands with `arch -x86_64` prepended, but it was the same. Unclear if it really forced rosetta or not.

**Comment by Gerrit0** [comment] 2021-02-01 02:48
> It works on node 15,

To me, this says it's a bug in Node, not in TypeDoc... an OOM caused by JS code should be reproducible across multiple node versions.

**Comment by orta** [comment] 2021-02-01 09:20
Does it make a difference if the terminal is running in rosetta?

**Comment by bleonard** [comment] 2021-02-01 16:56
I checked this box and ran it and got the same outcome.

<img width="267" alt="Screen Shot 2021-02-01 at 8 55 09 AM" src="https://user-images.githubusercontent.com/36106/106491008-43667b00-646b-11eb-8e32-645bd6945206.png">

**Comment by Gerrit0** [comment] 2021-02-02 13:52
I did some digging - this is a Node bug, nothing TypeDoc can do about it. 

https://github.com/facebook/create-react-app/issues/10090#issuecomment-733168991

**Comment by evantahler** [comment] 2021-02-02 16:39
It's *always* `chokidar` causing problems...  Anyway, thank you for your awesome work on Typedoc.  Actionhero uses it (https://docs.actionherojs.com), Node-Resque uses is (https://node-resque.actionherojs.com), and @grouparoo uses it (https://docs.grouparoo.com)! 

Feel free to close this issue... or keep it open so you can point others here.

**Comment by Gerrit0** [comment] 2021-02-03 02:26
I'll go ahead and close it, still possible to point people towards it :)

I'm glad you've found TypeDoc useful!

**Closed by Gerrit0** 2021-02-03 02:26 UTC
Labels: bug, external

**Comment by vincelamm** [comment] 2021-05-18 10:01
node 14.17 solved the issue for me on m1. 14.16 still crashes.
I have had no issues on node 16 so far.

**Comment by sperka** [comment] 2022-10-12 04:14
`NODE_OPTIONS=--max_old_space_size=16384` solved the issue on m1
