### ISSUE TITLE
Error trying to generate documentation

### ISSUE THREAD

**Issue by yarkovaleksei** [TypeStrong/typedoc#820] opened 2018-07-21 14:26 UTC
`$ typedoc --out ./docs ./src

Using TypeScript 2.7.2 from /home/user/.nvm/versions/node/v9.8.0/lib/node_modules/typedoc/node_modules/typescript/lib
Error: /home/user/git/frontend/node_modules/@types/sinon/index.d.ts(488)
 ';' expected.
`

**Comment by taoqf** [comment] 2018-07-30 07:49
same issue

**Comment by Hoten** [comment] 2018-08-02 04:59
same

**Comment by Hoten** [comment] 2018-08-02 05:13
Seems the default behavior of ignoring these files is broken (seems it is meant to be opt in given `--includeDeclarations` exists).

**Comment by liuxh0** [comment] 2018-08-16 14:31
+1

**Comment by ali-habibzadeh** [comment] 2018-08-23 18:58
+1

**Comment by daniellacosse** [comment] 2019-02-14 16:49
+1 for me still, sinon

**Comment by Gerrit0** [comment] 2019-02-16 05:56
Thanks for the repro to look at.

I haven't cloned to check it out, but I did notice that you are using `^0.11.1`, if you update to `^0.14.2` you may find that the types work.

**Comment by daniellacosse** [comment] 2019-02-16 13:34
oh shooot sorry thanks

**Comment by Gerrit0** [comment] 2019-05-11 01:02
Closing this since as far as I can tell the error was caused by a TypeScript version incompatibility. As TypeDoc (master at least) is now on 3.4, this should not longer be an issue.

In July 2018 TypeDoc was on TypeScript version 2.7.2. The Sinon types at that time required conditional types, which were introduced in 2.8 [git blame](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/3981bfe29e2b246f5edc426914ed77518fe9e2f7/types/sinon/index.d.ts#L489)

**Closed by Gerrit0** 2019-05-11 01:02 UTC
Labels: Priority: 1, bug, help wanted, needs reproduction
