### ISSUE TITLE
Make a configuration option to default to having "Inherited" unchecked.

### ISSUE THREAD

**Issue by rob4226** [TypeStrong/typedoc#1698] opened 2021-09-17 01:16 UTC
Since there is no way to exclude inherited members from TypeDoc, can we at least add an option to default to having the "Inherited" checkbox unchecked?  In some situations, it makes it very hard to read some docs with tons of inherited members that don't really help and actually hide what the documents are really for.  Thanks.

![Screenshot 2021-09-16 210613](https://user-images.githubusercontent.com/16749343/133708150-e4362ed0-01c2-49c7-ad62-433240bf1550.jpg)

**Comment by Gerrit0** [comment] 2021-09-18 14:40
Duplicate of #307

**Closed** 2021-09-18 14:41 UTC
Labels: enhancement
