### ISSUE TITLE
Suggestion: Use the terms "Namespace" and "Module" rather than "Module" and "External Module"

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#878] opened 2018-10-08 17:38 UTC
TypeScript moved away from the terms "Internal Module" and "External Module" in favor of "Namespace" and "Module" to more clearly align with ECMAScript parlance. It would be nice to at least have an option to configure this, if not to just have this be the default behavior.

**Comment by aciccarello** [comment] 2018-10-08 17:49
👍 I agree. Closing as a dupe of #109

**Closed by aciccarello** 2018-10-08 17:49 UTC
