### ISSUE TITLE
Allow categorizing exported types in the sidebar

### ISSUE THREAD

**Issue by thislooksfun** [TypeStrong/typedoc#1532] opened 2021-03-11 23:25 UTC
## Search Terms

sidebar, category, exports, class, interface

## Problem

When exporting a large project the sidebar quickly gets overloaded with semi-internal types that 99% of users won't use, thus burying the types that are actually relevant.

## Suggested Solution

It would be great if adding `@category foo-bar` to an exported type would split the sidebar into groups. This would then allow for use cases such as:
- having a single main export (function/class/etc) that is prominently separated from all the helper types
- logically grouping like types that have disparate names
- segregating away all the types that are only exposed for the <1% of people who might need them

**Comment by Gerrit0** [comment] 2021-03-12 22:41
Dupe of #1332, which I could have sworn I replied to with the issues I ran into the last time I tried this... but apparently not

Essentially what stopped this then was that the sidebar then no longer matched the page order... but I just ran another test, and apparently this would correct this problem.

It wouldn't fix the "functions with multiple categories get rendered twice" issue, but that's fine. I don't have a good solution for this yet.
![image](https://user-images.githubusercontent.com/19329837/111005961-1b5f1700-8349-11eb-9976-4b296a4765c0.png)

**Comment by thislooksfun** [comment] 2021-03-12 22:50
Yeah I thought it might be a dupe of that, but it was so terse I couldn't fully tell.

I know it's only semi-related, but I would consider the double-declaration a feature, not a bug. If it's in multiple categories I would honestly *expect* it to do that.

**Comment by Gerrit0** [comment] 2021-03-12 23:30
That's... a really good point. Okay, yeah, I'd be fine treating that as a feature. Just need to fix the duplicate `id` in the page for links in 0.21 then.

**Comment by tmigone** [comment] 2022-01-20 14:58
Any news regarding this feature @Gerrit0? thanks for the tool btw it's awesome

**Comment by Gerrit0** [comment] 2022-01-23 01:55
Nope, I don't think this was something that was done in #1794, shouldn't be too difficult to do though.

**Comment by minh2605** [comment] 2023-02-23 04:35
is this feature available now ? Don't see any news regarding this feature

**Closed** 2023-04-22 15:35 UTC
Labels: enhancement, help wanted

**Comment by symil** [comment] 2024-01-09 17:51
For anyone wondering, it took me some time to figure out how to actually use the feature, and in the end it was as simple as adding the following to my `typedoc.json` (you can change the category names of course):

```
{
    "navigation": {
        "includeCategories": true
    },
    "defaultCategory": "Utility",
    "categoryOrder": [
        "Core",
        "Utility",
        "Advanced",
        "Internal"
    ]
}
```

Btw a thousand times thank you for this great tool! It's quite simple to use and the generated documentation is really good looking and easy to navigate.
