### ISSUE TITLE
Support `#` in links

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1629] opened 2021-07-15 11:44 UTC
## Search Terms

link, member

## Problem

JSDoc and JavaDoc use `#` to refer to instance methods and fields of a class (e.g. `Class#method`) while `.` is used for static methods and fields (e.g. `Class.staticField`).

TypeDoc does not support this. Even worse, TypeDoc doesn't even error or warn when encountering such links.

![image](https://user-images.githubusercontent.com/20878432/125781959-d2cc607e-c40a-4006-a6ed-3997602cabeb.png)

([input code](https://github.com/RunDevelopment/refa/blob/cc7ede839f5b1ab865b64396da6158b7fccefb76/src/fa-types.ts#L143), [referenced method](https://github.com/RunDevelopment/refa/blob/cc7ede839f5b1ab865b64396da6158b7fccefb76/src/fa-types.ts#L115))

## Suggested Solution

Support `#`. TypeDoc doesn't really differentiate between static and instance members right now, so treating `#` as a `.` should work.

---

Also, is it a bug that invalid links are just printed as is? Shouldn't there be a warning since it's an invalid reference?

**Comment by Gerrit0** [comment] 2021-07-16 16:43
> Shouldn't there be a warning since it's an invalid reference?

There is, if you turn on [listInvalidSymbolLinks](https://typedoc.org/guides/options/#listinvalidsymbollinks)

Semi-dupe of #488

**Closed** 2022-06-26 20:26 UTC
Labels: enhancement
