### ISSUE TITLE
Typedoc runs typedoc.js file with wrong options

### ISSUE THREAD

**Issue by Alessar** [TypeStrong/typedoc#1074] opened 2019-07-19 16:04 UTC
* Repro steps:
`npm install typedoc`
Create `"typedoc":"typedoc"` in `run` section in `package.json`
Create file `typedoc.js` with possible options
`npm run typedoc`
* Expected:
Documentation should be generated
* Actual:
`typedoc.js` opened in external text editor
* Thoughts:
Maybe `typedocs.js` is executed without specifying executor like `js` or `node` and in this case `*.js` files interprets as it was setup in system by default. But in this case maybe it is needed to provide additional options for run via `js` or `node` executor for example.

**Comment by Gerrit0** [comment] 2019-07-22 12:01
This doesn't make much sense to me. TypeDoc doesn't execute the file as an external program. It requires it. I'll try to find some time to look at this either this week or this weekend.

https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/options/readers/typedoc.ts

**Comment by aciccarello** [comment] 2019-07-26 00:43
@Alessar It isn't clear what is causing the problem you are encountering since the issue doesn't describe your configuration options. You may want to try configuring typedoc with a typedoc.json file. See our [Installation guide](https://typedoc.org/guides/installation/) for more information.

Since we can't help you with the information provided I'm going to close this but you are welcome to reply with more information if you still need help. We'll reopen if there is a bug.

**Closed by aciccarello** 2019-07-26 00:43 UTC
Labels: bug, needs reproduction

**Comment by Alessar** [comment] 2019-07-30 16:57
@aciccarello Unfortunately I cannot understand what you wait from me.
All repro steps I already provided. Options in file is `{ }` - is it possible options?

And what additionally I found:
`typedoc --help` shows:
`--options Specify a js option file that should be loaded. If not specified TypeDoc will look for 'typedoc.js' in the current directory.`
But you and documentation mentioned `typedoc.json` file.
So I don't know to whom I should trust?

So my repro steps contains file `typedoc.JS` according self-documentation from script.
@Gerrit0 Did you try to reproduce discribed reprosteps with such file?

**Comment by Gerrit0** [comment] 2019-07-31 02:38
This is really weird, but doesn't appear to directly be a TypeDoc problem (though we probably should switch to follow the webpack/rollup/a bunch of other tools that recommend `tool.config.js` for config files, as our current recommendation clearly causes some confusion)

When you do `npm run typedoc` npm:
1. Adds `node_modules/.bin` to your path
1. Starts `cmd.exe` (or whatever you have specified with `script-shell`, see npm docs)
1. Sends the process the value of the `typedoc` key

Even though you will have `typedoc.cmd` in your path (npm includes `typedoc` for Unix systems and `typedoc.cmd` for Windows in the `node_modules/.bin` folder) `cmd.exe` apparently has some "special" behavior. If you specify the name of a file (with or without an extension) for some file extensions (including .js, but not .json), it will try to open the file in your default editor *before* searching for a path to execute.*

I'm guessing this is something leftover from the DOS days. Very unexpected behavior for me!

There are a couple of easy fixes:
1. Rename `typedoc.js` to something else, like `typedoc.config.js` and tell TypeDoc to look there with `--options typedoc.config.js`
1. Tell npm to use something besides `cmd.exe` as your shell. I ran `npm config set script-shell "%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe"` and everything worked as expected when running, even without renaming the `typedoc.js` file.

\* does not apply for builtin commands like `echo`

**Comment by aciccarello** [comment] 2019-07-31 14:18
@Alessar Sorry for the confusion in the help output. We should get that cleaned up. The `typedoc.json` is our recommended approach. If you need dynamic configuration, use the [programatic api](https://typedoc.org/guides/installation/#node-module) which imports typedoc as a node module.
