### ISSUE TITLE
How to set public path?

### ISSUE THREAD

**Issue by RohitRox** [TypeStrong/typedoc#1087] opened 2019-08-07 14:51 UTC
- [X] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

How can I set the public path for assets and links in the generated doc site?
I cannot seem to find an option for it.

**Comment by aciccarello** [comment] 2019-08-07 15:11
Hello @RohitRox, can you explain more about what you are attempting to accomplish?

**Comment by RohitRox** [comment] 2019-08-07 15:44
Hi @aciccarello, I want to host the docs generated by typedoc in a specific url path.
Let's say something like `myproject.com/pkgs/docs/app-kit`, in this scenario, if I put contents of typedoc generated folder to be served at that path,  the requests to styles and other pages will break.
I guess I am looking for something like webpack's publicPath that can be configured.

**Comment by aciccarello** [comment] 2019-08-07 16:02
TypeDoc uses relative paths so it shouldn't need to set a public path. You can use `[[ReflectionName]]` to reference other classes, variables, ect. and the links will be automatically generated. I need to check asset links.

**Comment by RohitRox** [comment] 2019-08-07 16:16
Hmm.. I see the all of the links in templates uses `relativeURL`, even the the links to assets. I was wondering if we could tweak it somehow to tell it to add desired prefix/path; in my case `/pkgs/docs/app-kit` or `http://myproject.com/pkgs/docs/app-kit`, by passing some config key to tell it to prefix or is there a way to extend/override the helper method.

**Comment by aciccarello** [comment] 2019-08-07 16:22
Sorry, that's currently not possible without defining a custom theme. I'm going to mark this as a duplicate of #940 so we can track progress there.

**Closed by aciccarello** 2019-08-07 16:23 UTC
Labels: question
