### ISSUE TITLE
Multiple Markdown files rendered into HTML?

### ISSUE THREAD

**Issue by dtgriscom** [TypeStrong/typedoc#797] opened 2018-06-15 13:27 UTC
I'm using TypeDoc to generate HTML output. I'm writing a long Markdown file giving an overview of my project, and it's being automatically included as the TypeDoc index page. Problem: the Markdown file is getting very, very long, and I'd like to break it up into multiple files, with the index page giving a 10,000 foot (3,000 meter?) view with links to the detail pages.

I tried adding a Markdown file link to the index file...

`[This is a link](./Events.md)`

... and TypeDoc rendered the link...

`<p><a href="./Events.md">This is a link</a></p>`

... but (perhaps not surprisingly) it didn't copy the Events.md file into the final doc folder, and even if it had I'd want Events to be rendered as HTML and framed by the standard TypeDoc items (e.g. header, globals listing, etc).

Is there a way for TypeDoc to specify additional Markdown pages that are rendered into HTML pages? Ideally, these pages would appear in a Table of Contents page, and "XXXXX.md" links would be converted to "XXXXX.html", but that could fairly easily be worked around by hand.

**Comment by aciccarello** [comment] 2018-06-20 04:51
Great question. Currently this is not possible. I'll mark this as a duplicate of #247 and we can track this there.

**Closed by aciccarello** 2018-06-20 04:51 UTC
