### ISSUE TITLE
Errors: C:/git/test-project/typings/node/node.d.ts(176)  Type expected.

### ISSUE THREAD

**Issue by kruncher** [TypeStrong/typedoc#193] opened 2016-03-06 17:47 UTC
When I try to use TypeDoc I just seem to get lots of errors (see below).

It seems like it's using an older version of TypeScript. I am very new to TypeScript so I'm not sure if I am using newer TypeScript features that simply weren't around in 1.6.2.

Is there anything that I can do to workaround this? or do I need to wait for the next version of TypeDoc?

Many thanks

```
λ typedoc -out ./docs/ .

Using TypeScript 1.6.2 from C:\Users\Me\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
Error: C:/git/test-project/lib/AliasMap.d.ts(211)
 Type expected.
Error: C:/git/test-project/lib/Environment.d.ts(196)
 Type expected.
Error: C:/git/test-project/node_modules/rxjs/util/MapPolyfill.d.ts(5)
 Type expected.
Error: C:/git/test-project/src/AliasMap.ts(332)
 Type expected.
Error: C:/git/test-project/src/AliasMap.ts(332)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(341)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(342)
 ':' expected.
Error: C:/git/test-project/src/AliasMap.ts(342)
 ',' expected.
Error: C:/git/test-project/src/AliasMap.ts(346)
 Declaration or statement expected.
Error: C:/git/test-project/src/AliasMap.ts(346)
 ',' expected.
Error: C:/git/test-project/src/AliasMap.ts(346)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(346)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(367)
 Declaration or statement expected.
Error: C:/git/test-project/src/AliasMap.ts(367)
 ',' expected.
Error: C:/git/test-project/src/AliasMap.ts(367)
 ',' expected.
Error: C:/git/test-project/src/AliasMap.ts(367)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(367)
 ';' expected.
Error: C:/git/test-project/src/AliasMap.ts(395)
 Declaration or statement expected.
Error: C:/git/test-project/src/Environment.ts(387)
 Type expected.
Error: C:/git/test-project/src/Environment.ts(387)
 ';' expected.
Error: C:/git/test-project/src/Environment.ts(397)
 Declaration or statement expected.
Error: C:/git/test-project/typings/node/node.d.ts(176)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(177)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(178)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(179)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(180)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(181)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(223)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(224)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(225)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(226)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(227)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(462)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(463)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(464)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(465)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(466)
 Type expected.
Error: C:/git/test-project/typings/node/node.d.ts(467)
 Type expected.
```

**Comment by 0815fox** [comment] 2016-03-10 09:06
Same issue here with node.d.ts from DefinitelyTyped. Seems that version 1.6.2 of tsc does not understand the syntax used in node.d.ts from DefinitelyTyped.

**Comment by emin93** [comment] 2016-04-20 19:30
Anyone of you found a fix for that? I still have this issue and can't a fix.

**Comment by 0815fox** [comment] 2016-04-20 21:34
Sorry, I did not continue to research on that. I did not yet find a working documentation generator tool for typescript.

**Comment by 0815fox** [comment] 2016-04-20 21:40
Oh, there seems to be a pull request since 3 days: https://github.com/TypeStrong/typedoc/pull/204

**Comment by emin93** [comment] 2016-04-21 20:10
Oh that's nice, let's hope they'll merge the pull request soon.

**Comment by samvv** [comment] 2016-04-28 16:04
Same here.

**Comment by born2net** [comment] 2016-04-29 01:20
I can't believe TS doesn't have a doc generator that works with TS 1.5+ .... thought TS was more popular ,,, maybe I was wrong :/

**Comment by WasabiFan** [comment] 2016-04-29 02:01
See #204 for discussion on this and related issues. Specifically, **the first post has instructions to point your project at a fixed version of this library** until everything is ready for it to be properly merged.

**Comment by born2net** [comment] 2016-04-29 02:04
tx!!!

**Comment by Gerrit0** [comment] 2019-05-14 03:28
Closing as this was caused by an outdated version of TypeDoc requiring an even more outdated version of TypeScript. Neither versions are relevant anymore.

**Closed by Gerrit0** 2019-05-14 03:28 UTC
Labels: bug
